use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Map, Value};

use super::{PUBLIC_ALIASES, is_identifier};

pub(super) fn generate(contracts: &[(&'static str, Value)]) -> String {
    let mut output = String::from("// Generated by `just codegen`. Do not edit.\n\n");
    for &(root_name, ref schema) in contracts {
        let context = SchemaContext::new(root_name, schema);
        for (definition, value) in &context.definitions {
            output.push_str("type ");
            output.push_str(&context.definition_name(definition));
            output.push_str(" = ");
            output.push_str(&typescript_type(value, &context, 0));
            output.push_str(";\n\n");
        }
        output.push_str("export type ");
        output.push_str(root_name);
        output.push_str(" = ");
        output.push_str(&typescript_type(schema, &context, 0));
        output.push_str(";\n\n");
    }
    for &(alias, root, definition) in PUBLIC_ALIASES {
        output.push_str("export type ");
        output.push_str(alias);
        output.push_str(" = ");
        output.push_str(root);
        output.push_str(definition);
        output.push_str(";\n");
    }
    output
}

struct SchemaContext<'a> {
    root_name: &'static str,
    definitions: BTreeMap<String, &'a Value>,
}

impl<'a> SchemaContext<'a> {
    fn new(root_name: &'static str, schema: &'a Value) -> Self {
        let definitions = schema
            .get("$defs")
            .and_then(Value::as_object)
            .map(|values| {
                values
                    .iter()
                    .map(|(name, value)| (name.clone(), value))
                    .collect()
            })
            .unwrap_or_default();
        Self {
            root_name,
            definitions,
        }
    }

    fn definition_name(&self, definition: &str) -> String {
        format!("{}{}", self.root_name, definition)
    }

    fn reference_name(&self, reference: &str) -> Option<String> {
        if reference == "#" {
            return Some(self.root_name.to_owned());
        }
        reference
            .strip_prefix("#/$defs/")
            .map(|definition| self.definition_name(definition))
    }
}

fn typescript_type(schema: &Value, context: &SchemaContext<'_>, depth: usize) -> String {
    let Some(object) = schema.as_object() else {
        return "unknown".to_owned();
    };
    if let Some(reference) = object.get("$ref").and_then(Value::as_str)
        && let Some(name) = context.reference_name(reference)
    {
        return name;
    }
    if let Some(value) = object.get("const") {
        return json_literal(value);
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return join_types(values.iter().map(json_literal), " | ");
    }
    for (key, separator) in [("oneOf", " | "), ("anyOf", " | "), ("allOf", " & ")] {
        if let Some(values) = object.get(key).and_then(Value::as_array) {
            return join_types(
                values
                    .iter()
                    .map(|value| typescript_type(value, context, depth)),
                separator,
            );
        }
    }
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        return join_types(
            kinds
                .iter()
                .map(|kind| typescript_primitive(kind, object, context, depth)),
            " | ",
        );
    }
    if let Some(kind) = object.get("type") {
        return typescript_primitive(kind, object, context, depth);
    }
    if object.contains_key("properties") {
        return typescript_object(object, context, depth);
    }
    "unknown".to_owned()
}

fn typescript_primitive(
    kind: &Value,
    schema: &Map<String, Value>,
    context: &SchemaContext<'_>,
    depth: usize,
) -> String {
    match kind.as_str() {
        Some("null") => "null".to_owned(),
        Some("boolean") => "boolean".to_owned(),
        Some("integer" | "number") => "number".to_owned(),
        Some("string") => "string".to_owned(),
        Some("array") => {
            let item = schema.get("items").map_or_else(
                || "unknown".to_owned(),
                |value| typescript_type(value, context, depth),
            );
            format!("Array<{item}>")
        }
        Some("object") => typescript_object(schema, context, depth),
        _ => "unknown".to_owned(),
    }
}

fn typescript_object(
    schema: &Map<String, Value>,
    context: &SchemaContext<'_>,
    depth: usize,
) -> String {
    let properties = schema.get("properties").and_then(Value::as_object);
    let additional = schema.get("additionalProperties");
    let Some(properties) = properties else {
        return match additional {
            Some(Value::Object(value)) => format!(
                "Record<string, {}>",
                typescript_type(&Value::Object(value.clone()), context, depth)
            ),
            Some(Value::Bool(false)) => "Record<string, never>".to_owned(),
            _ => "Record<string, unknown>".to_owned(),
        };
    };
    if properties.is_empty() {
        return match additional {
            Some(Value::Object(value)) => format!(
                "Record<string, {}>",
                typescript_type(&Value::Object(value.clone()), context, depth)
            ),
            Some(Value::Bool(false)) => "Record<string, never>".to_owned(),
            _ => "Record<string, unknown>".to_owned(),
        };
    }
    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let indent = "  ".repeat(depth);
    let child_indent = "  ".repeat(depth + 1);
    let mut output = String::from("{\n");
    for (name, property) in properties {
        output.push_str(&child_indent);
        output.push_str(&typescript_property_name(name));
        if !required.contains(name.as_str()) {
            output.push('?');
        }
        output.push_str(": ");
        output.push_str(&typescript_type(property, context, depth + 1));
        output.push_str(";\n");
    }
    if additional.is_some_and(|value| value != &Value::Bool(false)) {
        output.push_str(&child_indent);
        output.push_str("[key: string]: unknown;\n");
    }
    output.push_str(&indent);
    output.push('}');
    output
}

fn typescript_property_name(name: &str) -> String {
    if is_identifier(name) {
        name.to_owned()
    } else {
        serde_json::to_string(name).unwrap_or_else(|_| "\"field\"".to_owned())
    }
}

fn join_types(types: impl Iterator<Item = String>, separator: &str) -> String {
    let types = types.collect::<Vec<_>>();
    match types.as_slice() {
        [] => "never".to_owned(),
        [single] => single.clone(),
        _ => format!("({})", types.join(separator)),
    }
}

fn json_literal(value: &Value) -> String {
    serde_json::to_string(value).unwrap_or_else(|_| "unknown".to_owned())
}
