# Generated by `cargo run -p xtask -- codegen`. Do not edit.

from typing import Literal, TypeAlias, TypedDict

class ArtifactExportRequestArtifactVariantOneOf1(TypedDict):
    kind: Literal["pdf"]
    options: ArtifactExportRequestPdfOptions

class ArtifactExportRequestArtifactVariantOneOf2(TypedDict):
    kind: Literal["markdown"]
    options: ArtifactExportRequestMarkdownOptions

class ArtifactExportRequestArtifactVariantOneOf3(TypedDict):
    kind: Literal["zip"]

class ArtifactExportRequestArtifactVariantOneOf4(TypedDict):
    kind: Literal["self-extracting"]

class ArtifactExportRequestArtifactVariantOneOf5(TypedDict):
    kind: Literal["mhtml"]

ArtifactExportRequestArtifactVariant: TypeAlias = ArtifactExportRequestArtifactVariantOneOf1 | ArtifactExportRequestArtifactVariantOneOf2 | ArtifactExportRequestArtifactVariantOneOf3 | ArtifactExportRequestArtifactVariantOneOf4 | ArtifactExportRequestArtifactVariantOneOf5

ArtifactExportRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

class _ArtifactExportRequestMarkdownOptionsOptional(TypedDict, total=False):
    frontMatter: bool

class ArtifactExportRequestMarkdownOptions(_ArtifactExportRequestMarkdownOptionsOptional):
    pass

class _ArtifactExportRequestPdfOptionsOptional(TypedDict, total=False):
    landscape: bool
    preferCssPageSize: bool

class ArtifactExportRequestPdfOptions(_ArtifactExportRequestPdfOptionsOptional):
    pass

class ArtifactExportRequest(TypedDict):
    baseName: str
    conflict: ArtifactExportRequestConflictPolicy
    outputDirectory: str
    variants: list[ArtifactExportRequestArtifactVariant]

ArtifactExportResultArtifactVariantKind: TypeAlias = Literal["pdf", "markdown", "zip", "self-extracting", "mhtml"]

class ArtifactExportResultArtifactVariantVerification(TypedDict):
    bytes: int
    contentValid: bool
    kind: ArtifactExportResultArtifactVariantKind
    passed: bool
    sha256: str
    structureValid: bool

class ArtifactExportResultExportedArtifact(TypedDict):
    bytes: int
    entrypoint: str
    kind: ArtifactExportResultArtifactVariantKind
    path: str
    sha256: str
    verification: ArtifactExportResultArtifactVariantVerification

class ArtifactExportResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class ArtifactExportResult(TypedDict):
    policySha256: str
    resources: ArtifactExportResultResourceSummary
    schemaVersion: int
    sourceArtifactSha256: str
    variants: list[ArtifactExportResultExportedArtifact]

class ArtifactManifestArtifactFormat(TypedDict):
    kind: ArtifactManifestArtifactKind
    version: int

ArtifactManifestArtifactKind: TypeAlias = Literal["html"]

class ArtifactManifestBrowserEnvironment(TypedDict):
    colorScheme: ArtifactManifestColorScheme
    locale: str
    reducedMotion: ArtifactManifestReducedMotion
    timezone: str
    userAgent: ArtifactManifestUserAgentPolicy
    viewport: ArtifactManifestViewport

class _ArtifactManifestBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class ArtifactManifestBrowserInfo(_ArtifactManifestBrowserInfoOptional):
    product: ArtifactManifestBrowserProduct
    protocolVersion: str
    source: ArtifactManifestBrowserSource
    version: str

ArtifactManifestBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

ArtifactManifestBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

ArtifactManifestColorScheme: TypeAlias = Literal["light", "dark"]

ArtifactManifestExternalReason: TypeAlias = Literal["policy", "unsupported-scheme", "explicitly-preserved"]

class ArtifactManifestManifestGenerator(TypedDict):
    name: str
    version: str

class ArtifactManifestManifestSource(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

class ArtifactManifestManifestVerification(TypedDict):
    level: ArtifactManifestVerificationPolicy
    networkRequests: int
    passed: bool

ArtifactManifestOmissionReason: TypeAlias = Literal["non-rendering", "sanitized", "sensitive", "limit"]

ArtifactManifestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class ArtifactManifestResourceError(TypedDict):
    code: str
    message: str
    retryable: bool

class ArtifactManifestResourceOutcomeOneOf1(TypedDict):
    bytes: int
    digest: str
    kind: Literal["embedded"]
    mediaType: str

class ArtifactManifestResourceOutcomeOneOf2(TypedDict):
    kind: Literal["external"]
    reason: ArtifactManifestExternalReason
    url: str
    urlSha256: str

class ArtifactManifestResourceOutcomeOneOf3(TypedDict):
    kind: Literal["omitted"]
    reason: ArtifactManifestOmissionReason

class ArtifactManifestResourceOutcomeOneOf4(TypedDict):
    error: ArtifactManifestResourceError
    kind: Literal["failed"]

ArtifactManifestResourceOutcome: TypeAlias = ArtifactManifestResourceOutcomeOneOf1 | ArtifactManifestResourceOutcomeOneOf2 | ArtifactManifestResourceOutcomeOneOf3 | ArtifactManifestResourceOutcomeOneOf4

class _ArtifactManifestResourceProvenanceOptional(TypedDict, total=False):
    redirects: list[str]
    status: int | None

class ArtifactManifestResourceProvenance(_ArtifactManifestResourceProvenanceOptional):
    finalUrl: str
    finalUrlSha256: str
    receivedBytes: int
    source: ArtifactManifestResourceRetrievalSource

class _ArtifactManifestResourceRecordOptional(TypedDict, total=False):
    provenance: ArtifactManifestResourceProvenance | None

class ArtifactManifestResourceRecord(_ArtifactManifestResourceRecordOptional):
    frameId: int
    id: int
    outcome: ArtifactManifestResourceOutcome
    requestedUrl: str
    requestedUrlSha256: str

ArtifactManifestResourceRetrievalSource: TypeAlias = Literal["inline-data", "observed-response", "browser-context-fetch", "owning-frame-read", "local-file-read"]

class ArtifactManifestResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _ArtifactManifestStructuralRepairOptional(TypedDict, total=False):
    scriptSha256: str | None

class ArtifactManifestStructuralRepair(_ArtifactManifestStructuralRepairOptional):
    applied: bool

class ArtifactManifestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class ArtifactManifestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

ArtifactManifestUserAgentPolicy: TypeAlias = ArtifactManifestUserAgentPolicyOneOf1 | ArtifactManifestUserAgentPolicyOneOf2

ArtifactManifestVerificationPolicy: TypeAlias = Literal["static", "offline"]

class ArtifactManifestViewState(TypedDict):
    scrollX: str
    scrollY: str

class ArtifactManifestViewport(TypedDict):
    height: int
    scale: int
    width: int

class _ArtifactManifestOptional(TypedDict, total=False):
    resourceRecords: list[ArtifactManifestResourceRecord]
    warningCodes: list[str]

class ArtifactManifest(_ArtifactManifestOptional):
    browser: ArtifactManifestBrowserInfo
    capturedAt: str
    environment: ArtifactManifestBrowserEnvironment
    format: ArtifactManifestArtifactFormat
    frames: int
    generator: ArtifactManifestManifestGenerator
    policySha256: str
    resources: ArtifactManifestResourceSummary
    schemaVersion: int
    source: ArtifactManifestManifestSource
    structuralRepair: ArtifactManifestStructuralRepair
    verification: ArtifactManifestManifestVerification
    viewState: ArtifactManifestViewState

ArtifactVariantVerificationArtifactVariantKind: TypeAlias = Literal["pdf", "markdown", "zip", "self-extracting", "mhtml"]

class ArtifactVariantVerification(TypedDict):
    bytes: int
    contentValid: bool
    kind: ArtifactVariantVerificationArtifactVariantKind
    passed: bool
    sha256: str
    structureValid: bool

class BatchRequestArtifactSpecOneOf1(TypedDict):
    kind: Literal["html"]
    options: BatchRequestHtmlArtifactSpec

BatchRequestArtifactSpec: TypeAlias = BatchRequestArtifactSpecOneOf1

class BatchRequestArtifactTargetOneOf1(TypedDict):
    kind: Literal["file"]
    value: str

class BatchRequestArtifactTargetOneOf2Value(TypedDict):
    maxBytes: int

class BatchRequestArtifactTargetOneOf2(TypedDict):
    kind: Literal["bytes"]
    value: BatchRequestArtifactTargetOneOf2Value

BatchRequestArtifactTarget: TypeAlias = BatchRequestArtifactTargetOneOf1 | BatchRequestArtifactTargetOneOf2

class BatchRequestBatchJob(TypedDict):
    id: str
    request: BatchRequestCaptureRequest

class _BatchRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: BatchRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class BatchRequestBrowserCookie(_BatchRequestBrowserCookieOptional):
    name: str
    value: str

class BatchRequestBrowserEnvironment(TypedDict):
    colorScheme: BatchRequestColorScheme
    locale: str
    reducedMotion: BatchRequestReducedMotion
    timezone: str
    userAgent: BatchRequestUserAgentPolicy
    viewport: BatchRequestViewport

class BatchRequestBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class BatchRequestBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

class BatchRequestBrowserSpecOneOf3(TypedDict):
    kind: Literal["remote"]
    value: str

BatchRequestBrowserSpec: TypeAlias = BatchRequestBrowserSpecOneOf1 | BatchRequestBrowserSpecOneOf2 | BatchRequestBrowserSpecOneOf3

class _BatchRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[BatchRequestBrowserCookie]
    headers: list[BatchRequestRequestHeader]

class BatchRequestCaptureCredentials(_BatchRequestCaptureCredentialsOptional):
    pass

class BatchRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    cssImportDepth: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resources: int
    totalResourceBytes: int

class _BatchRequestCapturePolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: BatchRequestOptimizationPolicy
    scope: BatchRequestCaptureScope
    selector: str | None

class BatchRequestCapturePolicy(_BatchRequestCapturePolicyOptional):
    missingResources: BatchRequestMissingResourcePolicy
    preservePasswordValues: bool

class _BatchRequestCaptureRequestOptional(TypedDict, total=False):
    credentials: BatchRequestCaptureCredentials
    headed: bool | None

class BatchRequestCaptureRequest(_BatchRequestCaptureRequestOptional):
    artifact: BatchRequestArtifactSpec
    browser: BatchRequestBrowserSpec
    capture: BatchRequestCapturePolicy
    diagnostics: BatchRequestDiagnosticsPolicy
    environment: BatchRequestBrowserEnvironment
    limits: BatchRequestCaptureLimits
    network: BatchRequestNetworkPolicy
    readiness: BatchRequestReadinessPolicy
    url: str
    verification: BatchRequestVerificationPolicy

BatchRequestCaptureScope: TypeAlias = Literal["page", "selection"]

BatchRequestColorScheme: TypeAlias = Literal["light", "dark"]

BatchRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

BatchRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _BatchRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None
    screenshots: bool

class BatchRequestDiagnosticsPolicy(_BatchRequestDiagnosticsPolicyOptional):
    pass

class BatchRequestHtmlArtifactSpec(TypedDict):
    conflict: BatchRequestConflictPolicy
    target: BatchRequestArtifactTarget

class BatchRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class BatchRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: BatchRequestViewportSweepPolicy

BatchRequestLazyLoadPolicy: TypeAlias = BatchRequestLazyLoadPolicyOneOf1 | BatchRequestLazyLoadPolicyOneOf2

BatchRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class BatchRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class BatchRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class BatchRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class BatchRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: BatchRequestNetworkRules

BatchRequestNetworkPolicy: TypeAlias = BatchRequestNetworkPolicyOneOf1 | BatchRequestNetworkPolicyOneOf2 | BatchRequestNetworkPolicyOneOf3 | BatchRequestNetworkPolicyOneOf4

class _BatchRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class BatchRequestNetworkRules(_BatchRequestNetworkRulesOptional):
    pass

class _BatchRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class BatchRequestOptimizationPolicy(_BatchRequestOptimizationPolicyOptional):
    pass

BatchRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class BatchRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: BatchRequestLazyLoadPolicy
    mode: BatchRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

BatchRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class BatchRequestRequestHeader(TypedDict):
    name: str
    value: str

class _BatchRequestResumeOptionsOptional(TypedDict, total=False):
    retryFailed: bool

class BatchRequestResumeOptions(_BatchRequestResumeOptionsOptional):
    manifest: str

class BatchRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class BatchRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

BatchRequestUserAgentPolicy: TypeAlias = BatchRequestUserAgentPolicyOneOf1 | BatchRequestUserAgentPolicyOneOf2

BatchRequestVerificationPolicy: TypeAlias = Literal["static", "offline"]

class BatchRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class BatchRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _BatchRequestOptional(TypedDict, total=False):
    concurrency: int
    resume: BatchRequestResumeOptions | None

class BatchRequest(_BatchRequestOptional):
    jobs: list[BatchRequestBatchJob]

class BatchResultArtifactResultOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class BatchResultArtifactResultOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

BatchResultArtifactResult: TypeAlias = BatchResultArtifactResultOneOf1 | BatchResultArtifactResultOneOf2

class _BatchResultCaptureResultOptional(TypedDict, total=False):
    warnings: list[BatchResultCaptureWarning]

class BatchResultCaptureResult(_BatchResultCaptureResultOptional):
    artifact: BatchResultArtifactResult
    captureId: str
    resources: BatchResultResourceSummary
    schemaVersion: int
    source: BatchResultSourceSummary
    status: BatchResultCaptureTerminalStatus
    timings: BatchResultCaptureTimings
    verification: BatchResultVerificationResult

BatchResultCaptureTerminalStatus: TypeAlias = Literal["succeeded", "cancelled", "failed"]

class BatchResultCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    resources: int
    settle: int
    total: int
    transform: int
    validation: int
    verification: int

class _BatchResultCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class BatchResultCaptureWarning(_BatchResultCaptureWarningOptional):
    code: str
    message: str

BatchResultErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

BatchResultPageKnotErrorDetails: TypeAlias = dict[str, object]

class _BatchResultPageKnotErrorOptional(TypedDict, total=False):
    details: BatchResultPageKnotErrorDetails
    diagnosticsPath: str | None
    source: BatchResultPageKnotError | None

class BatchResultPageKnotError(_BatchResultPageKnotErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: BatchResultErrorStage

class BatchResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _BatchResultResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: BatchResultPageKnotError | None
    ordinal: int | None
    url: str | None

class BatchResultResumeJobRecord(_BatchResultResumeJobRecordOptional):
    requestSha256: str
    status: BatchResultResumeJobStatus

BatchResultResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

class BatchResultScheduledCaptureOutcomeOneOf1(TypedDict):
    id: str
    requestSha256: str
    result: BatchResultCaptureResult
    status: Literal["succeeded"]

class BatchResultScheduledCaptureOutcomeOneOf2(TypedDict):
    error: BatchResultPageKnotError
    id: str
    requestSha256: str
    status: Literal["failed"]

class BatchResultScheduledCaptureOutcomeOneOf3(TypedDict):
    id: str
    record: BatchResultResumeJobRecord
    status: Literal["resumed"]

BatchResultScheduledCaptureOutcome: TypeAlias = BatchResultScheduledCaptureOutcomeOneOf1 | BatchResultScheduledCaptureOutcomeOneOf2 | BatchResultScheduledCaptureOutcomeOneOf3

class BatchResultSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

BatchResultVerificationPolicy: TypeAlias = Literal["static", "offline"]

class _BatchResultVerificationResultOptional(TypedDict, total=False):
    attemptedUrls: list[str]
    frameFailures: list[int]
    pageErrors: list[str]

class BatchResultVerificationResult(_BatchResultVerificationResultOptional):
    artifactSha256: str
    bytes: int
    level: BatchResultVerificationPolicy
    networkRequests: int
    passed: bool
    schemaVersion: int
    stable: bool

class BatchResult(TypedDict):
    failed: int
    outcomes: list[BatchResultScheduledCaptureOutcome]
    planSha256: str
    resumed: int
    schemaVersion: int
    succeeded: int

class BrowserDoctorReportBrowserCandidate(TypedDict):
    activeLeases: int
    browser: BrowserDoctorReportBrowserInfo
    priority: int
    reasonCode: str
    state: BrowserDoctorReportBrowserCandidateState

BrowserDoctorReportBrowserCandidateState: TypeAlias = Literal["selected", "compatible", "incompatible", "shadowed"]

class _BrowserDoctorReportBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class BrowserDoctorReportBrowserInfo(_BrowserDoctorReportBrowserInfoOptional):
    product: BrowserDoctorReportBrowserProduct
    protocolVersion: str
    source: BrowserDoctorReportBrowserSource
    version: str

BrowserDoctorReportBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

BrowserDoctorReportBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _BrowserDoctorReportCapabilityCheckOptional(TypedDict, total=False):
    capabilities: list[str]
    missingCapabilities: list[str]
    peerVersion: str | None

class BrowserDoctorReportCapabilityCheck(_BrowserDoctorReportCapabilityCheckOptional):
    compatible: bool
    hostVersion: str

BrowserDoctorReportConfigProvenance: TypeAlias = Literal["flag", "environment", "explicit-config", "profile", "user-config", "default"]

class BrowserDoctorReportEffectiveConfigValue(TypedDict):
    field: str
    provenance: BrowserDoctorReportConfigProvenance
    redacted: bool
    value: object

class _BrowserDoctorReportManagedBrowserStateOptional(TypedDict, total=False):
    installedRevisions: list[str]
    selectedRevision: str | None

class BrowserDoctorReportManagedBrowserState(_BrowserDoctorReportManagedBrowserStateOptional):
    cacheDir: str
    catalogVersion: str

class BrowserDoctorReportNetworkPolicySummary(TypedDict):
    permitsLoopbackInitialOrigin: bool
    permitsPrivateAddresses: bool
    profile: str
    revalidatesRedirects: bool

class _BrowserDoctorReportOutputCapabilityOptional(TypedDict, total=False):
    reasonCode: str | None

class BrowserDoctorReportOutputCapability(_BrowserDoctorReportOutputCapabilityOptional):
    atomicCreate: bool
    atomicReplace: bool
    directory: str
    writable: bool

class _BrowserDoctorReportRecoveryActionOptional(TypedDict, total=False):
    arguments: list[str]

class BrowserDoctorReportRecoveryAction(_BrowserDoctorReportRecoveryActionOptional):
    code: str
    command: str
    description: str

class _BrowserDoctorReportOptional(TypedDict, total=False):
    candidates: list[BrowserDoctorReportBrowserCandidate]
    configuration: list[BrowserDoctorReportEffectiveConfigValue]
    recovery: list[BrowserDoctorReportRecoveryAction]
    selected: BrowserDoctorReportBrowserInfo | None

class BrowserDoctorReport(_BrowserDoctorReportOptional):
    collector: BrowserDoctorReportCapabilityCheck
    managedCache: BrowserDoctorReportManagedBrowserState
    network: BrowserDoctorReportNetworkPolicySummary
    output: BrowserDoctorReportOutputCapability
    ready: bool
    schemaVersion: int

BrowserOperationResultBrowserAction: TypeAlias = Literal["install", "list", "remove"]

class BrowserOperationResultBrowserCandidate(TypedDict):
    activeLeases: int
    browser: BrowserOperationResultBrowserInfo
    priority: int
    reasonCode: str
    state: BrowserOperationResultBrowserCandidateState

BrowserOperationResultBrowserCandidateState: TypeAlias = Literal["selected", "compatible", "incompatible", "shadowed"]

class _BrowserOperationResultBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class BrowserOperationResultBrowserInfo(_BrowserOperationResultBrowserInfoOptional):
    product: BrowserOperationResultBrowserProduct
    protocolVersion: str
    source: BrowserOperationResultBrowserSource
    version: str

BrowserOperationResultBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

BrowserOperationResultBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _BrowserOperationResultOptional(TypedDict, total=False):
    browser: BrowserOperationResultBrowserInfo | None
    candidates: list[BrowserOperationResultBrowserCandidate]
    revision: str | None

class BrowserOperationResult(_BrowserOperationResultOptional):
    action: BrowserOperationResultBrowserAction
    cacheDir: str
    schemaVersion: int

class _CaptureEventBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class CaptureEventBrowserInfo(_CaptureEventBrowserInfoOptional):
    product: CaptureEventBrowserProduct
    protocolVersion: str
    source: CaptureEventBrowserSource
    version: str

CaptureEventBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

CaptureEventBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _CaptureEventCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CaptureEventCaptureWarning(_CaptureEventCaptureWarningOptional):
    code: str
    message: str

CaptureEventErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

CaptureEventPageKnotErrorDetails: TypeAlias = dict[str, object]

class _CaptureEventPageKnotErrorOptional(TypedDict, total=False):
    details: CaptureEventPageKnotErrorDetails
    diagnosticsPath: str | None
    source: CaptureEventPageKnotError | None

class CaptureEventPageKnotError(_CaptureEventPageKnotErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: CaptureEventErrorStage

CaptureEventVerificationPolicy: TypeAlias = Literal["static", "offline"]

class _CaptureEventVerificationResultOptional(TypedDict, total=False):
    attemptedUrls: list[str]
    frameFailures: list[int]
    pageErrors: list[str]

class CaptureEventVerificationResult(_CaptureEventVerificationResultOptional):
    artifactSha256: str
    bytes: int
    level: CaptureEventVerificationPolicy
    networkRequests: int
    passed: bool
    schemaVersion: int
    stable: bool

class CaptureEventOneOf1(TypedDict):
    captureId: str
    type: Literal["capture.started"]

class CaptureEventOneOf2(TypedDict):
    browser: CaptureEventBrowserInfo
    captureId: str
    type: Literal["browser.ready"]

class CaptureEventOneOf3(TypedDict):
    captureId: str
    type: Literal["navigation.started"]
    url: str

CaptureEventOneOf4 = TypedDict("CaptureEventOneOf4", {"captureId": str, "from": str, "status": int, "to": str, "type": Literal["navigation.redirected"]})

class CaptureEventOneOf5(TypedDict):
    captureId: str
    elapsed: int
    milestone: str
    type: Literal["readiness.changed"]

class CaptureEventOneOf6(TypedDict):
    captureId: str
    frameId: int
    nodes: int
    type: Literal["frame.collected"]

class CaptureEventOneOf7(TypedDict):
    captureId: str
    resourceId: int
    type: Literal["resource.discovered"]

class CaptureEventOneOf8(TypedDict):
    bytes: int
    captureId: str
    completed: int
    discovered: int
    type: Literal["resource.progress"]

class CaptureEventOneOf9(TypedDict):
    captureId: str
    type: Literal["transform.started"]

class CaptureEventOneOf10(TypedDict):
    bytes: int
    captureId: str
    type: Literal["artifact.encoding"]

class CaptureEventOneOf11(TypedDict):
    captureId: str
    type: Literal["verification.started"]

class CaptureEventOneOf12(TypedDict):
    captureId: str
    type: Literal["warning"]
    warning: CaptureEventCaptureWarning

class CaptureEventOneOf13(TypedDict):
    captureId: str
    type: Literal["capture.succeeded"]
    verification: CaptureEventVerificationResult

class CaptureEventOneOf14(TypedDict):
    captureId: str
    error: CaptureEventPageKnotError
    type: Literal["capture.failed"]

class CaptureEventOneOf15(TypedDict):
    captureId: str
    type: Literal["capture.cancelled"]

CaptureEvent: TypeAlias = CaptureEventOneOf1 | CaptureEventOneOf2 | CaptureEventOneOf3 | CaptureEventOneOf4 | CaptureEventOneOf5 | CaptureEventOneOf6 | CaptureEventOneOf7 | CaptureEventOneOf8 | CaptureEventOneOf9 | CaptureEventOneOf10 | CaptureEventOneOf11 | CaptureEventOneOf12 | CaptureEventOneOf13 | CaptureEventOneOf14 | CaptureEventOneOf15

CapturePolicyCaptureScope: TypeAlias = Literal["page", "selection"]

CapturePolicyMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class _CapturePolicyOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class CapturePolicyOptimizationPolicy(_CapturePolicyOptimizationPolicyOptional):
    pass

class _CapturePolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: CapturePolicyOptimizationPolicy
    scope: CapturePolicyCaptureScope
    selector: str | None

class CapturePolicy(_CapturePolicyOptional):
    missingResources: CapturePolicyMissingResourcePolicy
    preservePasswordValues: bool

class CaptureRequestArtifactSpecOneOf1(TypedDict):
    kind: Literal["html"]
    options: CaptureRequestHtmlArtifactSpec

CaptureRequestArtifactSpec: TypeAlias = CaptureRequestArtifactSpecOneOf1

class CaptureRequestArtifactTargetOneOf1(TypedDict):
    kind: Literal["file"]
    value: str

class CaptureRequestArtifactTargetOneOf2Value(TypedDict):
    maxBytes: int

class CaptureRequestArtifactTargetOneOf2(TypedDict):
    kind: Literal["bytes"]
    value: CaptureRequestArtifactTargetOneOf2Value

CaptureRequestArtifactTarget: TypeAlias = CaptureRequestArtifactTargetOneOf1 | CaptureRequestArtifactTargetOneOf2

class _CaptureRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: CaptureRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class CaptureRequestBrowserCookie(_CaptureRequestBrowserCookieOptional):
    name: str
    value: str

class CaptureRequestBrowserEnvironment(TypedDict):
    colorScheme: CaptureRequestColorScheme
    locale: str
    reducedMotion: CaptureRequestReducedMotion
    timezone: str
    userAgent: CaptureRequestUserAgentPolicy
    viewport: CaptureRequestViewport

class CaptureRequestBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class CaptureRequestBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

class CaptureRequestBrowserSpecOneOf3(TypedDict):
    kind: Literal["remote"]
    value: str

CaptureRequestBrowserSpec: TypeAlias = CaptureRequestBrowserSpecOneOf1 | CaptureRequestBrowserSpecOneOf2 | CaptureRequestBrowserSpecOneOf3

class _CaptureRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[CaptureRequestBrowserCookie]
    headers: list[CaptureRequestRequestHeader]

class CaptureRequestCaptureCredentials(_CaptureRequestCaptureCredentialsOptional):
    pass

class CaptureRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    cssImportDepth: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resources: int
    totalResourceBytes: int

class _CaptureRequestCapturePolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: CaptureRequestOptimizationPolicy
    scope: CaptureRequestCaptureScope
    selector: str | None

class CaptureRequestCapturePolicy(_CaptureRequestCapturePolicyOptional):
    missingResources: CaptureRequestMissingResourcePolicy
    preservePasswordValues: bool

CaptureRequestCaptureScope: TypeAlias = Literal["page", "selection"]

CaptureRequestColorScheme: TypeAlias = Literal["light", "dark"]

CaptureRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

CaptureRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _CaptureRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None
    screenshots: bool

class CaptureRequestDiagnosticsPolicy(_CaptureRequestDiagnosticsPolicyOptional):
    pass

class CaptureRequestHtmlArtifactSpec(TypedDict):
    conflict: CaptureRequestConflictPolicy
    target: CaptureRequestArtifactTarget

class CaptureRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class CaptureRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: CaptureRequestViewportSweepPolicy

CaptureRequestLazyLoadPolicy: TypeAlias = CaptureRequestLazyLoadPolicyOneOf1 | CaptureRequestLazyLoadPolicyOneOf2

CaptureRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class CaptureRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class CaptureRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class CaptureRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class CaptureRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: CaptureRequestNetworkRules

CaptureRequestNetworkPolicy: TypeAlias = CaptureRequestNetworkPolicyOneOf1 | CaptureRequestNetworkPolicyOneOf2 | CaptureRequestNetworkPolicyOneOf3 | CaptureRequestNetworkPolicyOneOf4

class _CaptureRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class CaptureRequestNetworkRules(_CaptureRequestNetworkRulesOptional):
    pass

class _CaptureRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class CaptureRequestOptimizationPolicy(_CaptureRequestOptimizationPolicyOptional):
    pass

CaptureRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class CaptureRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: CaptureRequestLazyLoadPolicy
    mode: CaptureRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

CaptureRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class CaptureRequestRequestHeader(TypedDict):
    name: str
    value: str

class CaptureRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class CaptureRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

CaptureRequestUserAgentPolicy: TypeAlias = CaptureRequestUserAgentPolicyOneOf1 | CaptureRequestUserAgentPolicyOneOf2

CaptureRequestVerificationPolicy: TypeAlias = Literal["static", "offline"]

class CaptureRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class CaptureRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _CaptureRequestOptional(TypedDict, total=False):
    credentials: CaptureRequestCaptureCredentials
    headed: bool | None

class CaptureRequest(_CaptureRequestOptional):
    artifact: CaptureRequestArtifactSpec
    browser: CaptureRequestBrowserSpec
    capture: CaptureRequestCapturePolicy
    diagnostics: CaptureRequestDiagnosticsPolicy
    environment: CaptureRequestBrowserEnvironment
    limits: CaptureRequestCaptureLimits
    network: CaptureRequestNetworkPolicy
    readiness: CaptureRequestReadinessPolicy
    url: str
    verification: CaptureRequestVerificationPolicy

class CaptureResultArtifactResultOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class CaptureResultArtifactResultOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

CaptureResultArtifactResult: TypeAlias = CaptureResultArtifactResultOneOf1 | CaptureResultArtifactResultOneOf2

CaptureResultCaptureTerminalStatus: TypeAlias = Literal["succeeded", "cancelled", "failed"]

class CaptureResultCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    resources: int
    settle: int
    total: int
    transform: int
    validation: int
    verification: int

class _CaptureResultCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CaptureResultCaptureWarning(_CaptureResultCaptureWarningOptional):
    code: str
    message: str

class CaptureResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class CaptureResultSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

CaptureResultVerificationPolicy: TypeAlias = Literal["static", "offline"]

class _CaptureResultVerificationResultOptional(TypedDict, total=False):
    attemptedUrls: list[str]
    frameFailures: list[int]
    pageErrors: list[str]

class CaptureResultVerificationResult(_CaptureResultVerificationResultOptional):
    artifactSha256: str
    bytes: int
    level: CaptureResultVerificationPolicy
    networkRequests: int
    passed: bool
    schemaVersion: int
    stable: bool

class _CaptureResultOptional(TypedDict, total=False):
    warnings: list[CaptureResultCaptureWarning]

class CaptureResult(_CaptureResultOptional):
    artifact: CaptureResultArtifactResult
    captureId: str
    resources: CaptureResultResourceSummary
    schemaVersion: int
    source: CaptureResultSourceSummary
    status: CaptureResultCaptureTerminalStatus
    timings: CaptureResultCaptureTimings
    verification: CaptureResultVerificationResult

class CrawlRequestArtifactSpecOneOf1(TypedDict):
    kind: Literal["html"]
    options: CrawlRequestHtmlArtifactSpec

CrawlRequestArtifactSpec: TypeAlias = CrawlRequestArtifactSpecOneOf1

class CrawlRequestArtifactTargetOneOf1(TypedDict):
    kind: Literal["file"]
    value: str

class CrawlRequestArtifactTargetOneOf2Value(TypedDict):
    maxBytes: int

class CrawlRequestArtifactTargetOneOf2(TypedDict):
    kind: Literal["bytes"]
    value: CrawlRequestArtifactTargetOneOf2Value

CrawlRequestArtifactTarget: TypeAlias = CrawlRequestArtifactTargetOneOf1 | CrawlRequestArtifactTargetOneOf2

class _CrawlRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: CrawlRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class CrawlRequestBrowserCookie(_CrawlRequestBrowserCookieOptional):
    name: str
    value: str

class CrawlRequestBrowserEnvironment(TypedDict):
    colorScheme: CrawlRequestColorScheme
    locale: str
    reducedMotion: CrawlRequestReducedMotion
    timezone: str
    userAgent: CrawlRequestUserAgentPolicy
    viewport: CrawlRequestViewport

class _CrawlRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[CrawlRequestBrowserCookie]
    headers: list[CrawlRequestRequestHeader]

class CrawlRequestCaptureCredentials(_CrawlRequestCaptureCredentialsOptional):
    pass

class CrawlRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    cssImportDepth: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resources: int
    totalResourceBytes: int

class _CrawlRequestCapturePolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: CrawlRequestOptimizationPolicy
    scope: CrawlRequestCaptureScope
    selector: str | None

class CrawlRequestCapturePolicy(_CrawlRequestCapturePolicyOptional):
    missingResources: CrawlRequestMissingResourcePolicy
    preservePasswordValues: bool

CrawlRequestCaptureScope: TypeAlias = Literal["page", "selection"]

CrawlRequestColorScheme: TypeAlias = Literal["light", "dark"]

CrawlRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

CrawlRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _CrawlRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None
    screenshots: bool

class CrawlRequestDiagnosticsPolicy(_CrawlRequestDiagnosticsPolicyOptional):
    pass

class CrawlRequestHtmlArtifactSpec(TypedDict):
    conflict: CrawlRequestConflictPolicy
    target: CrawlRequestArtifactTarget

class CrawlRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class CrawlRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: CrawlRequestViewportSweepPolicy

CrawlRequestLazyLoadPolicy: TypeAlias = CrawlRequestLazyLoadPolicyOneOf1 | CrawlRequestLazyLoadPolicyOneOf2

class CrawlRequestLocalBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class CrawlRequestLocalBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

CrawlRequestLocalBrowserSpec: TypeAlias = CrawlRequestLocalBrowserSpecOneOf1 | CrawlRequestLocalBrowserSpecOneOf2

class _CrawlRequestLocalCaptureRequestOptional(TypedDict, total=False):
    credentials: CrawlRequestCaptureCredentials
    headed: bool | None

class CrawlRequestLocalCaptureRequest(_CrawlRequestLocalCaptureRequestOptional):
    artifact: CrawlRequestArtifactSpec
    browser: CrawlRequestLocalBrowserSpec
    capture: CrawlRequestCapturePolicy
    diagnostics: CrawlRequestDiagnosticsPolicy
    environment: CrawlRequestBrowserEnvironment
    limits: CrawlRequestCaptureLimits
    network: CrawlRequestNetworkPolicy
    readiness: CrawlRequestReadinessPolicy
    url: str
    verification: CrawlRequestVerificationPolicy

CrawlRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class CrawlRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class CrawlRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class CrawlRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class CrawlRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: CrawlRequestNetworkRules

CrawlRequestNetworkPolicy: TypeAlias = CrawlRequestNetworkPolicyOneOf1 | CrawlRequestNetworkPolicyOneOf2 | CrawlRequestNetworkPolicyOneOf3 | CrawlRequestNetworkPolicyOneOf4

class _CrawlRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class CrawlRequestNetworkRules(_CrawlRequestNetworkRulesOptional):
    pass

class _CrawlRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class CrawlRequestOptimizationPolicy(_CrawlRequestOptimizationPolicyOptional):
    pass

CrawlRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class CrawlRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: CrawlRequestLazyLoadPolicy
    mode: CrawlRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

CrawlRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class CrawlRequestRequestHeader(TypedDict):
    name: str
    value: str

class _CrawlRequestResumeOptionsOptional(TypedDict, total=False):
    retryFailed: bool

class CrawlRequestResumeOptions(_CrawlRequestResumeOptionsOptional):
    manifest: str

class CrawlRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class CrawlRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

CrawlRequestUserAgentPolicy: TypeAlias = CrawlRequestUserAgentPolicyOneOf1 | CrawlRequestUserAgentPolicyOneOf2

CrawlRequestVerificationPolicy: TypeAlias = Literal["static", "offline"]

class CrawlRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class CrawlRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _CrawlRequestOptional(TypedDict, total=False):
    concurrency: int
    maximumDepth: int
    maximumPages: int
    resume: CrawlRequestResumeOptions | None
    sameOrigin: bool

class CrawlRequest(_CrawlRequestOptional):
    outputDirectory: str
    seed: CrawlRequestLocalCaptureRequest

class CrawlResultArtifactResultOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class CrawlResultArtifactResultOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

CrawlResultArtifactResult: TypeAlias = CrawlResultArtifactResultOneOf1 | CrawlResultArtifactResultOneOf2

class _CrawlResultCaptureResultOptional(TypedDict, total=False):
    warnings: list[CrawlResultCaptureWarning]

class CrawlResultCaptureResult(_CrawlResultCaptureResultOptional):
    artifact: CrawlResultArtifactResult
    captureId: str
    resources: CrawlResultResourceSummary
    schemaVersion: int
    source: CrawlResultSourceSummary
    status: CrawlResultCaptureTerminalStatus
    timings: CrawlResultCaptureTimings
    verification: CrawlResultVerificationResult

CrawlResultCaptureTerminalStatus: TypeAlias = Literal["succeeded", "cancelled", "failed"]

class CrawlResultCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    resources: int
    settle: int
    total: int
    transform: int
    validation: int
    verification: int

class _CrawlResultCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CrawlResultCaptureWarning(_CrawlResultCaptureWarningOptional):
    code: str
    message: str

class CrawlResultCrawlPageOutcome(TypedDict):
    capture: CrawlResultScheduledCaptureOutcome
    depth: int
    ordinal: int
    url: str

CrawlResultErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

CrawlResultPageKnotErrorDetails: TypeAlias = dict[str, object]

class _CrawlResultPageKnotErrorOptional(TypedDict, total=False):
    details: CrawlResultPageKnotErrorDetails
    diagnosticsPath: str | None
    source: CrawlResultPageKnotError | None

class CrawlResultPageKnotError(_CrawlResultPageKnotErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: CrawlResultErrorStage

class CrawlResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _CrawlResultResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: CrawlResultPageKnotError | None
    ordinal: int | None
    url: str | None

class CrawlResultResumeJobRecord(_CrawlResultResumeJobRecordOptional):
    requestSha256: str
    status: CrawlResultResumeJobStatus

CrawlResultResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

class CrawlResultScheduledCaptureOutcomeOneOf1(TypedDict):
    id: str
    requestSha256: str
    result: CrawlResultCaptureResult
    status: Literal["succeeded"]

class CrawlResultScheduledCaptureOutcomeOneOf2(TypedDict):
    error: CrawlResultPageKnotError
    id: str
    requestSha256: str
    status: Literal["failed"]

class CrawlResultScheduledCaptureOutcomeOneOf3(TypedDict):
    id: str
    record: CrawlResultResumeJobRecord
    status: Literal["resumed"]

CrawlResultScheduledCaptureOutcome: TypeAlias = CrawlResultScheduledCaptureOutcomeOneOf1 | CrawlResultScheduledCaptureOutcomeOneOf2 | CrawlResultScheduledCaptureOutcomeOneOf3

class CrawlResultSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

CrawlResultVerificationPolicy: TypeAlias = Literal["static", "offline"]

class _CrawlResultVerificationResultOptional(TypedDict, total=False):
    attemptedUrls: list[str]
    frameFailures: list[int]
    pageErrors: list[str]

class CrawlResultVerificationResult(_CrawlResultVerificationResultOptional):
    artifactSha256: str
    bytes: int
    level: CrawlResultVerificationPolicy
    networkRequests: int
    passed: bool
    schemaVersion: int
    stable: bool

class CrawlResult(TypedDict):
    failed: int
    outcomes: list[CrawlResultCrawlPageOutcome]
    planSha256: str
    resumed: int
    schemaVersion: int
    succeeded: int

PageKnotErrorRecordErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

PageKnotErrorRecordDetails: TypeAlias = dict[str, object]

class _PageKnotErrorRecordOptional(TypedDict, total=False):
    details: PageKnotErrorRecordDetails
    diagnosticsPath: str | None
    source: PageKnotErrorRecord | None

class PageKnotErrorRecord(_PageKnotErrorRecordOptional):
    code: str
    message: str
    retryable: bool
    stage: PageKnotErrorRecordErrorStage

class ResumeManifestCrawlFrontierItem(TypedDict):
    depth: int
    ordinal: int
    url: str

ResumeManifestErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

ResumeManifestPageKnotErrorDetails: TypeAlias = dict[str, object]

class _ResumeManifestPageKnotErrorOptional(TypedDict, total=False):
    details: ResumeManifestPageKnotErrorDetails
    diagnosticsPath: str | None
    source: ResumeManifestPageKnotError | None

class ResumeManifestPageKnotError(_ResumeManifestPageKnotErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: ResumeManifestErrorStage

class _ResumeManifestResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: ResumeManifestPageKnotError | None
    ordinal: int | None
    url: str | None

class ResumeManifestResumeJobRecord(_ResumeManifestResumeJobRecordOptional):
    requestSha256: str
    status: ResumeManifestResumeJobStatus

ResumeManifestResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

ResumeManifestScheduleKind: TypeAlias = Literal["batch", "crawl"]

ResumeManifestJobs: TypeAlias = dict[str, ResumeManifestResumeJobRecord]

class _ResumeManifestOptional(TypedDict, total=False):
    frontier: list[ResumeManifestCrawlFrontierItem]
    jobs: ResumeManifestJobs
    pending: list[str]

class ResumeManifest(_ResumeManifestOptional):
    kind: ResumeManifestScheduleKind
    planSha256: str
    schemaVersion: int

VerificationResultVerificationPolicy: TypeAlias = Literal["static", "offline"]

class _VerificationResultOptional(TypedDict, total=False):
    attemptedUrls: list[str]
    frameFailures: list[int]
    pageErrors: list[str]

class VerificationResult(_VerificationResultOptional):
    artifactSha256: str
    bytes: int
    level: VerificationResultVerificationPolicy
    networkRequests: int
    passed: bool
    schemaVersion: int
    stable: bool

ArtifactVariant: TypeAlias = ArtifactExportRequestArtifactVariant
ArtifactVariantKind: TypeAlias = ArtifactVariantVerificationArtifactVariantKind
BatchJob: TypeAlias = BatchRequestBatchJob
BrowserInfo: TypeAlias = ArtifactManifestBrowserInfo
CaptureLimits: TypeAlias = CaptureRequestCaptureLimits
CaptureScope: TypeAlias = CapturePolicyCaptureScope
ConflictPolicy: TypeAlias = ArtifactExportRequestConflictPolicy
CrawlPageOutcome: TypeAlias = CrawlResultCrawlPageOutcome
ErrorStage: TypeAlias = PageKnotErrorRecordErrorStage
ExportedArtifact: TypeAlias = ArtifactExportResultExportedArtifact
MarkdownOptions: TypeAlias = ArtifactExportRequestMarkdownOptions
PdfOptions: TypeAlias = ArtifactExportRequestPdfOptions
ResumeOptions: TypeAlias = BatchRequestResumeOptions
ScheduledCaptureOutcome: TypeAlias = BatchResultScheduledCaptureOutcome
VerificationPolicy: TypeAlias = VerificationResultVerificationPolicy
Viewport: TypeAlias = CaptureRequestViewport
