use std::collections::{BTreeMap, BTreeSet};

use serde_json::{Map, Value};

use super::{PUBLIC_ALIASES, is_identifier};

#[derive(Clone)]
struct PythonType {
    name: String,
    schema: Value,
}

pub(super) fn generate(contracts: &[(&'static str, Value)]) -> Result<String, String> {
    let mut output = String::from(
        "# Generated by `cargo run -p xtask -- codegen`. Do not edit.\n\n\
         from typing import Literal, TypeAlias, TypedDict\n\n",
    );
    for &(root_name, ref schema) in contracts {
        let context = PythonContext::new(root_name, schema)?;
        for definition in &context.types {
            output.push_str(&python_definition(definition, &context)?);
            output.push('\n');
        }
    }
    for &(alias, root, definition) in PUBLIC_ALIASES {
        output.push_str(alias);
        output.push_str(": TypeAlias = ");
        output.push_str(root);
        output.push_str(definition);
        output.push('\n');
    }
    Ok(output)
}

struct PythonContext {
    root_name: &'static str,
    types: Vec<PythonType>,
    references: BTreeMap<String, String>,
    anonymous: BTreeMap<String, String>,
}

impl PythonContext {
    fn new(root_name: &'static str, schema: &Value) -> Result<Self, String> {
        let mut context = Self {
            root_name,
            types: Vec::new(),
            references: BTreeMap::from([("#".to_owned(), root_name.to_owned())]),
            anonymous: BTreeMap::new(),
        };
        if let Some(definitions) = schema.get("$defs").and_then(Value::as_object) {
            for name in definitions.keys() {
                context
                    .references
                    .insert(format!("#/$defs/{name}"), format!("{root_name}{name}"));
            }
            for (name, value) in definitions {
                context.register_named(format!("{root_name}{name}"), value.clone())?;
            }
        }
        context.register_named(root_name.to_owned(), schema.clone())?;
        Ok(context)
    }

    fn register_named(&mut self, name: String, schema: Value) -> Result<(), String> {
        if self.types.iter().any(|existing| existing.name == name) {
            return Ok(());
        }
        self.collect_anonymous(&name, &schema)?;
        self.types.push(PythonType { name, schema });
        Ok(())
    }

    fn collect_anonymous(&mut self, owner: &str, schema: &Value) -> Result<(), String> {
        let Some(object) = schema.as_object() else {
            return Ok(());
        };
        for key in ["oneOf", "anyOf", "allOf"] {
            if let Some(variants) = object.get(key).and_then(Value::as_array) {
                for (index, variant) in variants.iter().enumerate() {
                    self.register_anonymous(
                        format!("{owner}{}{}", pascal_case(key), index + 1),
                        variant,
                    )?;
                }
            }
        }
        if let Some(properties) = object.get("properties").and_then(Value::as_object) {
            for (name, property) in properties {
                self.register_anonymous(format!("{owner}{}", pascal_case(name)), property)?;
            }
        }
        if let Some(items) = object.get("items") {
            self.register_anonymous(format!("{owner}Item"), items)?;
        }
        Ok(())
    }

    fn register_anonymous(&mut self, name: String, schema: &Value) -> Result<(), String> {
        if is_inline_object(schema) {
            let key = schema_pointer_key(schema);
            self.anonymous.insert(key, name.clone());
            self.register_named(name, schema.clone())?;
        } else {
            self.collect_anonymous(&name, schema)?;
        }
        Ok(())
    }

    fn reference_name(&self, reference: &str) -> Result<String, String> {
        self.references.get(reference).cloned().ok_or_else(|| {
            format!(
                "unsupported schema reference {reference} in {}",
                self.root_name
            )
        })
    }

    fn anonymous_name(&self, schema: &Value) -> Option<&str> {
        self.anonymous
            .get(&schema_pointer_key(schema))
            .map(String::as_str)
    }
}

fn python_definition(definition: &PythonType, context: &PythonContext) -> Result<String, String> {
    if is_object_schema(&definition.schema) {
        return python_typed_dict(definition, context);
    }
    Ok(format!(
        "{}: TypeAlias = {}\n",
        definition.name,
        python_type(&definition.schema, context, Some(&definition.name))?
    ))
}

fn python_typed_dict(definition: &PythonType, context: &PythonContext) -> Result<String, String> {
    let object = definition
        .schema
        .as_object()
        .ok_or_else(|| format!("{} is not an object schema", definition.name))?;
    let Some(properties) = object.get("properties").and_then(Value::as_object) else {
        return Ok(format!(
            "{}: TypeAlias = {}\n",
            definition.name,
            python_object_type(object, context)?
        ));
    };
    if properties.is_empty() {
        return Ok(format!(
            "{}: TypeAlias = {}\n",
            definition.name,
            python_object_type(object, context)?
        ));
    }
    let required = object
        .get("required")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect::<BTreeSet<_>>();
    let required_fields = properties
        .iter()
        .filter(|(name, _)| required.contains(name.as_str()))
        .collect::<Vec<_>>();
    let optional_fields = properties
        .iter()
        .filter(|(name, _)| !required.contains(name.as_str()))
        .collect::<Vec<_>>();
    let all_identifiers = properties.keys().all(|name| is_python_identifier(name));
    if !all_identifiers {
        if !required_fields.is_empty() && !optional_fields.is_empty() {
            return Err(format!(
                "{} mixes required and optional fields with a Python keyword",
                definition.name
            ));
        }
        let fields = properties
            .iter()
            .map(|(name, schema)| {
                Ok(format!(
                    "{}: {}",
                    serde_json::to_string(name).map_err(|error| error.to_string())?,
                    python_type(schema, context, None)?
                ))
            })
            .collect::<Result<Vec<_>, String>>()?
            .join(", ");
        let total = if optional_fields.is_empty() {
            ""
        } else {
            ", total=False"
        };
        return Ok(format!(
            "{} = TypedDict({}, {{{fields}}}{total})\n",
            definition.name,
            serde_json::to_string(&definition.name).map_err(|error| error.to_string())?
        ));
    }
    let mut output = String::new();
    if !optional_fields.is_empty() {
        output.push_str("class _");
        output.push_str(&definition.name);
        output.push_str("Optional(TypedDict, total=False):\n");
        for (name, schema) in &optional_fields {
            output.push_str("    ");
            output.push_str(name);
            output.push_str(": ");
            output.push_str(&python_type(schema, context, None)?);
            output.push('\n');
        }
        output.push('\n');
    }
    output.push_str("class ");
    output.push_str(&definition.name);
    if optional_fields.is_empty() {
        output.push_str("(TypedDict):\n");
    } else {
        output.push_str("(_");
        output.push_str(&definition.name);
        output.push_str("Optional):\n");
    }
    if required_fields.is_empty() {
        output.push_str("    pass\n");
    } else {
        for (name, schema) in required_fields {
            output.push_str("    ");
            output.push_str(name);
            output.push_str(": ");
            output.push_str(&python_type(schema, context, None)?);
            output.push('\n');
        }
    }
    Ok(output)
}

fn python_type(
    schema: &Value,
    context: &PythonContext,
    current: Option<&str>,
) -> Result<String, String> {
    let Some(object) = schema.as_object() else {
        return Ok("object".to_owned());
    };
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        return context.reference_name(reference);
    }
    if let Some(value) = object.get("const") {
        return Ok(format!("Literal[{}]", python_literal(value)));
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return Ok(format!(
            "Literal[{}]",
            values
                .iter()
                .map(python_literal)
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    for key in ["oneOf", "anyOf"] {
        if let Some(values) = object.get(key).and_then(Value::as_array) {
            let variants = values
                .iter()
                .map(|value| {
                    if let Some(name) = context.anonymous_name(value) {
                        Ok(name.to_owned())
                    } else {
                        python_type(value, context, current)
                    }
                })
                .collect::<Result<Vec<_>, String>>()?;
            return Ok(match variants.as_slice() {
                [] => "object".to_owned(),
                [single] => single.clone(),
                _ => variants.join(" | "),
            });
        }
    }
    if let Some(values) = object.get("allOf").and_then(Value::as_array)
        && let Some(single) = values.first()
    {
        return python_type(single, context, current);
    }
    if is_inline_object(schema)
        && let Some(name) = context.anonymous_name(schema)
        && Some(name) != current
    {
        return Ok(name.to_owned());
    }
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        let variants = kinds
            .iter()
            .map(|kind| python_primitive(kind, object, context))
            .collect::<Result<Vec<_>, String>>()?;
        return Ok(variants.join(" | "));
    }
    if let Some(kind) = object.get("type") {
        return python_primitive(kind, object, context);
    }
    if object.contains_key("properties") {
        return context
            .anonymous_name(schema)
            .map(str::to_owned)
            .or_else(|| current.map(str::to_owned))
            .ok_or_else(|| format!("unnamed object schema in {}", context.root_name));
    }
    Ok("object".to_owned())
}

fn python_primitive(
    kind: &Value,
    schema: &Map<String, Value>,
    context: &PythonContext,
) -> Result<String, String> {
    Ok(match kind.as_str() {
        Some("null") => "None".to_owned(),
        Some("boolean") => "bool".to_owned(),
        Some("integer") => "int".to_owned(),
        Some("number") => "float".to_owned(),
        Some("string") => "str".to_owned(),
        Some("array") => {
            let item = schema.get("items").map_or_else(
                || Ok("object".to_owned()),
                |value| python_type(value, context, None),
            )?;
            format!("list[{item}]")
        }
        Some("object") => python_object_type(schema, context)?,
        _ => "object".to_owned(),
    })
}

fn python_object_type(
    schema: &Map<String, Value>,
    context: &PythonContext,
) -> Result<String, String> {
    match schema.get("additionalProperties") {
        Some(Value::Object(value)) => Ok(format!(
            "dict[str, {}]",
            python_type(&Value::Object(value.clone()), context, None)?
        )),
        _ => Ok("dict[str, object]".to_owned()),
    }
}

fn python_literal(value: &Value) -> String {
    match value {
        Value::Null => "None".to_owned(),
        Value::Bool(true) => "True".to_owned(),
        Value::Bool(false) => "False".to_owned(),
        Value::String(value) => format!("{value:?}"),
        _ => value.to_string(),
    }
}

fn is_object_schema(schema: &Value) -> bool {
    schema.as_object().is_some_and(|object| {
        object.contains_key("properties")
            || object.get("type").and_then(Value::as_str) == Some("object")
    })
}

fn is_inline_object(schema: &Value) -> bool {
    is_object_schema(schema) && schema.get("$ref").is_none()
}

fn schema_pointer_key(schema: &Value) -> String {
    serde_json::to_string(schema).unwrap_or_else(|_| "schema".to_owned())
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase = true;
    for character in value.chars() {
        if !character.is_ascii_alphanumeric() {
            uppercase = true;
            continue;
        }
        if uppercase {
            result.push(character.to_ascii_uppercase());
            uppercase = false;
        } else {
            result.push(character);
        }
    }
    result
}

fn is_python_identifier(value: &str) -> bool {
    is_identifier(value)
        && !matches!(
            value,
            "False"
                | "None"
                | "True"
                | "and"
                | "as"
                | "assert"
                | "async"
                | "await"
                | "break"
                | "class"
                | "continue"
                | "def"
                | "del"
                | "elif"
                | "else"
                | "except"
                | "finally"
                | "for"
                | "from"
                | "global"
                | "if"
                | "import"
                | "in"
                | "is"
                | "lambda"
                | "nonlocal"
                | "not"
                | "or"
                | "pass"
                | "raise"
                | "return"
                | "try"
                | "while"
                | "with"
                | "yield"
        )
}
