/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeCaptureEvents {
  next(): Promise<any | null>
}

export declare class NativeCaptureJob {
  get id(): string
  get status(): string
  events(): NativeCaptureEvents
  cancel(): void
  result(): Promise<any>
}

export declare class NativeOffprint {
  static create(options?: any | undefined | null): NativeOffprint
  get initializationError(): any | null
  capture(url: string, options?: any | undefined | null): Promise<any>
  request(url: string, options?: any | undefined | null): any
  start(request: any): Promise<NativeCaptureJob>
  batch(request: any): Promise<any>
  crawl(request: any): Promise<any>
  inspect(path: string): Promise<any>
  verify(path: string, options?: any | undefined | null): Promise<any>
  exportArtifacts(path: string, request: any): Promise<any>
  verifyFormat(path: string, format: string): Promise<any>
  ensureBrowser(): Promise<any>
  listBrowsers(): Promise<any>
  installBrowser(revision?: string | undefined | null): Promise<any>
  removeBrowser(revision: string, force: boolean): Promise<any>
  doctor(): Promise<any>
  closeIdleBrowser(): Promise<void>
  close(): Promise<void>
  closeBlocking(): void
}
