use super::ErrorCodeDefinition;
use crate::ErrorStage;

macro_rules! error_codes {
    ($(($code:literal, $stage:ident, $retryable:literal, $description:literal)),* $(,)?) => {
        &[
            $(ErrorCodeDefinition {
                code: $code,
                stage: ErrorStage::$stage,
                retryable: $retryable,
                description: $description,
            }),*
        ]
    };
}

#[rustfmt::skip]
pub const ERROR_CODE_REGISTRY: &[ErrorCodeDefinition] = error_codes![
    ("offprint.artifact.digest", Commit, false, "The staged artifact digest changed before commit."),
    ("offprint.artifact.head", Encoding, false, "The captured document has no HTML head element."),
    ("offprint.artifact.manifest", Encoding, false, "The artifact manifest could not be serialized."),
    ("offprint.artifact.policy", Encoding, false, "The artifact policy is inconsistent with the captured document."),
    ("offprint.artifact.read", Verification, true, "The artifact could not be read."),
    ("offprint.artifact.resource_summary", Encoding, false, "The artifact resource summary is incomplete."),
    ("offprint.artifact.sandbox", Encoding, false, "The sandboxed HTML artifact is inconsistent."),
    ("offprint.artifact.serialize", Encoding, false, "The HTML artifact could not be serialized."),
    ("offprint.artifact.size", Encoding, false, "The artifact exceeds a configured or platform byte limit."),
    ("offprint.binding.runtime", Internal, false, "A language binding runtime could not be started."),
    ("offprint.binding.serialization", Internal, false, "A language binding could not serialize a canonical record."),
    ("offprint.binding.shutdown", Shutdown, false, "A language binding shutdown ended before reporting its result."),
    ("offprint.binding.shutdown_timeout", Shutdown, true, "A language binding shutdown exceeded its deadline."),
    ("offprint.browser.acquisition", Internal, false, "Browser ownership was lost during acquisition."),
    ("offprint.browser.acquisition_cancelled", Shutdown, false, "Browser acquisition was cancelled during shutdown."),
    ("offprint.browser.active", Browser, true, "The selected managed browser has active leases or requires replacement."),
    ("offprint.browser.cdp_close_timeout", Browser, true, "The CDP transport did not close before its deadline."),
    ("offprint.browser.cdp_closed", Browser, true, "The CDP connection closed."),
    ("offprint.browser.cdp_command", Browser, false, "Chromium rejected a CDP command."),
    ("offprint.browser.cdp_connect", Browser, true, "Offprint could not connect to a CDP endpoint."),
    ("offprint.browser.cdp_decode", Browser, false, "A CDP message could not be decoded."),
    ("offprint.browser.cdp_encode", Browser, false, "A CDP command could not be encoded."),
    ("offprint.browser.cdp_event_lag", Browser, true, "A CDP event consumer exceeded its bounded buffer."),
    ("offprint.browser.cdp_event_limit", Browser, false, "A CDP event exceeded its byte limit."),
    ("offprint.browser.cdp_shape", Browser, false, "A CDP response did not match the pinned protocol shape."),
    ("offprint.browser.cdp_task", Browser, false, "The CDP transport task failed."),
    ("offprint.browser.cdp_timeout", Browser, true, "A CDP command exceeded its deadline."),
    ("offprint.browser.cdp_transport", Browser, true, "The CDP WebSocket transport failed."),
    ("offprint.browser.containment", Browser, false, "The owned browser process tree could not be contained."),
    ("offprint.browser.context", Internal, false, "The browser context lifecycle is internally inconsistent."),
    ("offprint.browser.devtools_port", Browser, false, "Chromium published an invalid DevTools port."),
    ("offprint.browser.devtools_url", Browser, false, "Chromium published an invalid DevTools endpoint."),
    ("offprint.browser.executable", Browser, false, "The selected browser executable is unavailable."),
    ("offprint.browser.incompatible", Browser, false, "The selected browser is incompatible with Offprint."),
    ("offprint.browser.install", Browser, false, "A managed browser installation needs attention."),
    ("offprint.browser.interception_closed", Resource, false, "Response interception closed before collection completed."),
    ("offprint.browser.interception_task", Navigation, false, "The network interception task failed."),
    ("offprint.browser.launch", Browser, true, "Chromium could not be launched."),
    ("offprint.browser.launch_timeout", Browser, true, "Chromium did not start before its deadline."),
    ("offprint.browser.management_unavailable", Browser, false, "The requested managed browser operation is unavailable."),
    ("offprint.browser.offline_verifier_unavailable", Browser, false, "Browser-backed offline verification is unavailable."),
    ("offprint.browser.pdf_unavailable", Encoding, false, "The selected browser backend cannot render PDF output."),
    ("offprint.browser.probe", Browser, true, "The browser executable probe failed."),
    ("offprint.browser.probe_timeout", Browser, true, "The browser executable probe exceeded its deadline."),
    ("offprint.browser.profile", Browser, false, "An ephemeral browser profile could not be created."),
    ("offprint.browser.resource_task", Resource, false, "A browser resource collection task failed."),
    ("offprint.browser.selection_conflict", Browser, false, "The browser selection options request incompatible ownership modes."),
    ("offprint.browser.shutdown", Shutdown, true, "Chromium could not be stopped cleanly."),
    ("offprint.browser.target_crashed", Navigation, true, "The Chromium target crashed during an active operation."),
    ("offprint.browser.terminate", Shutdown, true, "The owned Chromium process tree could not be terminated."),
    ("offprint.browser.unavailable", Browser, false, "No compatible browser is available."),
    ("offprint.browser.version", Browser, false, "The browser version could not be identified."),
    ("offprint.collector.base_url", Collection, false, "A collected frame has an invalid document base URL."),
    ("offprint.collector.capability", Collection, false, "The collector lacks a requested capability."),
    ("offprint.collector.chunk_checksum", Collection, true, "A collector chunk checksum is invalid."),
    ("offprint.collector.chunk_length", Collection, false, "A collector chunk length is inconsistent."),
    ("offprint.collector.chunk_limit", Collection, false, "A collector chunk exceeds the negotiated limit."),
    ("offprint.collector.chunk_owner", Collection, false, "A collector chunk belongs to another capture or frame."),
    ("offprint.collector.chunk_sequence", Collection, false, "Collector chunks are out of sequence."),
    ("offprint.collector.chunk_total", Collection, false, "The collector changed a declared chunk count."),
    ("offprint.collector.document", Collection, false, "The rendered document could not be collected."),
    ("offprint.collector.evaluate", Collection, false, "The in-page collector evaluation failed."),
    ("offprint.collector.payload_checksum", Collection, true, "A collector payload digest is invalid."),
    ("offprint.collector.payload_limit", Collection, false, "Collector payloads exceed the configured capture limit."),
    ("offprint.collector.protocol_major", Collection, false, "The collector protocol major version is incompatible."),
    ("offprint.collector.protocol_shape", Collection, false, "A collector message does not match the protocol shape."),
    ("offprint.collector.value", Collection, false, "The collector returned a value that could not cross the protocol boundary."),
    ("offprint.config.directory", Validation, false, "The Offprint configuration directory is unavailable."),
    ("offprint.config.field", Validation, false, "An Offprint environment variable is not recognized."),
    ("offprint.config.parse", Validation, false, "An Offprint configuration file contains invalid TOML."),
    ("offprint.config.profile", Validation, false, "The selected capture profile is undefined."),
    ("offprint.config.read", Validation, true, "An Offprint configuration file could not be read."),
    ("offprint.config.value", Validation, false, "An Offprint configuration value is invalid."),
    ("offprint.export.encode", Encoding, false, "An artifact format could not be encoded."),
    ("offprint.export.files", Encoding, false, "An artifact format exceeds its file count limit."),
    ("offprint.export.format", Validation, false, "The requested artifact format set is invalid."),
    ("offprint.export.markdown_asset", Encoding, false, "A Markdown asset is malformed or has an invalid relative path."),
    ("offprint.export.name", Validation, false, "The artifact export base name is invalid."),
    ("offprint.export.output", Commit, false, "An artifact format output could not be staged or committed."),
    ("offprint.export.pdf", Encoding, false, "Chromium returned an invalid PDF payload."),
    ("offprint.export.pdf_metadata", Encoding, false, "The PDF metadata record is incomplete or inconsistent."),
    ("offprint.export.pdf_semantics", Encoding, false, "The PDF semantic structure is unavailable or malformed."),
    ("offprint.export.size", Encoding, false, "An artifact format exceeds its byte limit."),
    ("offprint.export.source", Encoding, false, "An artifact format source is inconsistent with the verified HTML."),
    ("offprint.export.verify", Verification, false, "An artifact format failed its format-specific verifier."),
    ("offprint.export.zip", Encoding, false, "A ZIP artifact could not be encoded or decoded."),
    ("offprint.frame.collection", Collection, false, "A frame could not be collected into the capture graph."),
    ("offprint.frame.depth", Collection, false, "The captured frame graph exceeds its configured depth."),
    ("offprint.frame.detached", Collection, true, "An out-of-process frame detached before collection completed."),
    ("offprint.frame.limit", Collection, false, "The captured frame graph exceeds its configured count."),
    ("offprint.frame.nodes", Collection, false, "The captured frame graph exceeds its configured node budget."),
    ("offprint.frame.owner", Collection, false, "A captured node or frame has an inconsistent owner."),
    ("offprint.frame.topology", Collection, false, "The captured frame graph has an invalid topology."),
    ("offprint.input.arguments", Validation, false, "The command line is invalid."),
    ("offprint.input.artifact", Validation, false, "The artifact input is invalid for the requested operation."),
    ("offprint.input.browser_recycle", Validation, false, "The browser recycling limit is invalid."),
    ("offprint.input.browser_selection", Validation, false, "The selected browser policy is invalid for the requested operation."),
    ("offprint.input.cdp_url", Validation, false, "The remote browser endpoint URL is invalid."),
    ("offprint.input.concurrency", Validation, false, "The browser context concurrency limit is invalid."),
    ("offprint.input.credentials", Validation, false, "The capture credential input is invalid or insufficiently protected."),
    ("offprint.input.duration", Validation, false, "A command duration is invalid."),
    ("offprint.input.error_code", Validation, false, "An error code is malformed."),
    ("offprint.input.export_option", Validation, false, "An artifact export option does not apply to the selected formats."),
    ("offprint.input.file_root", Validation, false, "A file URL is outside the configured roots."),
    ("offprint.input.json", Validation, false, "A JSON command input is unreadable, oversized, or invalid."),
    ("offprint.input.limit", Validation, false, "A capture limit is invalid."),
    ("offprint.input.network_cidr", Validation, false, "A custom network CIDR is invalid."),
    ("offprint.input.output", Validation, false, "The output target is invalid."),
    ("offprint.input.path_encoding", Validation, false, "A filesystem path cannot be represented as UTF-8."),
    ("offprint.input.remote_file", Validation, false, "A remote browser capture addressed the coordinator filesystem."),
    ("offprint.input.remote_network_policy", Validation, false, "A remote browser capture selected a restricted network policy."),
    ("offprint.input.remote_verification_policy", Validation, false, "A remote browser capture selected browser-backed verification."),
    ("offprint.input.schema_version", Validation, false, "An input record uses an incompatible schema version."),
    ("offprint.input.selector_scope", Validation, false, "A capture request combines a DOM selector with active selection scope."),
    ("offprint.input.url", Validation, false, "The capture URL is invalid."),
    ("offprint.input.url_scheme", Validation, false, "The capture URL uses a blocked scheme."),
    ("offprint.input.value", Validation, false, "A language binding input does not match its public record."),
    ("offprint.input.verification_option", Validation, false, "A verification option does not apply to the selected artifact format."),
    ("offprint.input.viewport", Validation, false, "The browser viewport is invalid."),
    ("offprint.internal.panic", Internal, false, "A capture task panicked behind the runtime boundary."),
    ("offprint.navigation.address_blocked", Navigation, false, "The network policy blocked a resolved address."),
    ("offprint.navigation.dns", Navigation, true, "The navigation host resolved to no addresses."),
    ("offprint.navigation.dns_timeout", Navigation, true, "A network policy DNS decision exceeded its deadline."),
    ("offprint.navigation.failed", Navigation, true, "Chromium could not navigate to the requested page."),
    ("offprint.navigation.host", Navigation, false, "The navigation URL has no host."),
    ("offprint.navigation.policy_state", Navigation, false, "The navigation request has no validated network policy state."),
    ("offprint.navigation.popup", Navigation, false, "A popup target could not be rejected safely."),
    ("offprint.navigation.port", Navigation, false, "The navigation URL has no usable port."),
    ("offprint.navigation.proxy", Navigation, true, "The validated network proxy could not complete a request."),
    ("offprint.navigation.redirect_limit", Navigation, false, "Navigation exceeded the configured redirect count."),
    ("offprint.navigation.request_limit", Navigation, false, "Concurrent intercepted requests exceed the supported limit."),
    ("offprint.navigation.scheme", Navigation, false, "The network URL scheme is blocked."),
    ("offprint.navigation.url", Navigation, false, "Chromium reported an invalid navigation URL."),
    ("offprint.output.commit", Commit, true, "The verified artifact could not be committed."),
    ("offprint.output.diagnostics", Commit, true, "The sanitized diagnostic bundle could not be committed."),
    ("offprint.output.directory", Validation, false, "The output directory is unavailable."),
    ("offprint.output.exists", Validation, false, "The output path already exists."),
    ("offprint.output.flush", Encoding, true, "The staging artifact could not be flushed."),
    ("offprint.output.path", Validation, false, "The output path is invalid."),
    ("offprint.output.read", Verification, true, "The staging artifact could not be read."),
    ("offprint.output.staging", Encoding, true, "The staging artifact could not be created."),
    ("offprint.output.stderr", Commit, true, "Human diagnostics could not be written to stderr."),
    ("offprint.output.stdout", Commit, true, "A structured command result could not be written to stdout."),
    ("offprint.output.sync", Encoding, true, "The staging artifact could not be synchronized."),
    ("offprint.output.uniquify", Commit, false, "A unique output filename could not be selected."),
    ("offprint.readiness.request_count", Readiness, false, "The readiness tracker observed an inconsistent request count."),
    ("offprint.readiness.timeout", Readiness, true, "The page did not reach the requested readiness state before its deadline."),
    ("offprint.resource.css_cycle", Resource, false, "A stylesheet import graph contains a cycle."),
    ("offprint.resource.css_depth", Resource, false, "A stylesheet import graph exceeds its configured depth."),
    ("offprint.resource.css_encoding", Resource, false, "A captured stylesheet has an unsupported text encoding."),
    ("offprint.resource.data_url", Resource, false, "A captured data URL could not be decoded."),
    ("offprint.resource.decode", Resource, false, "A browser resource body could not be decoded."),
    ("offprint.resource.html_cycle", Resource, false, "An embedded HTML resource graph contains a cycle."),
    ("offprint.resource.html_depth", Resource, false, "An embedded HTML resource graph exceeds its configured depth."),
    ("offprint.resource.html_frame", Resource, false, "An embedded HTML resource contains a nested frame."),
    ("offprint.resource.html_serialize", Resource, false, "An embedded HTML document could not be serialized."),
    ("offprint.resource.identifier", Resource, false, "A resource identifier is absent from the graph."),
    ("offprint.resource.incomplete", Resource, false, "A resource graph contains unresolved references."),
    ("offprint.resource.limit", Resource, false, "A capture resource budget was exceeded."),
    ("offprint.resource.load", Resource, true, "Chromium could not load a required resource body."),
    ("offprint.resource.protocol_shape", Resource, false, "A browser resource response did not match the pinned protocol shape."),
    ("offprint.resource.rewrite", Resource, false, "A controlled resource reference could not be rewritten."),
    ("offprint.resource.scheme", Resource, false, "A resource reference uses an unsupported URL scheme."),
    ("offprint.resource.status", Resource, true, "A required resource returned an unsuccessful HTTP status."),
    ("offprint.resource.store", Internal, false, "The capture content store is internally inconsistent."),
    ("offprint.resource.stream", Resource, true, "A required resource stream ended with an error."),
    ("offprint.resource.svg_cycle", Resource, false, "An SVG resource graph contains a cycle."),
    ("offprint.resource.svg_depth", Resource, false, "An SVG resource graph exceeds its configured depth."),
    ("offprint.resource.svg_parse", Resource, false, "A captured SVG document has no usable root element."),
    ("offprint.resource.svg_serialize", Resource, false, "A transformed SVG document could not be serialized."),
    ("offprint.resource.terminal", Resource, false, "A resource received more than one terminal outcome."),
    ("offprint.resource.url", Resource, false, "A captured resource URL is invalid."),
    ("offprint.runtime.acquisition", Internal, false, "Runtime ownership was lost during acquisition."),
    ("offprint.runtime.cancelled", Shutdown, false, "The active capture was cancelled."),
    ("offprint.runtime.capture_unavailable", Internal, false, "The capture runtime is unavailable."),
    ("offprint.runtime.closed", Shutdown, false, "The Offprint service is closed."),
    ("offprint.runtime.interrupted", Shutdown, false, "The active command received an interruption signal."),
    ("offprint.runtime.job", Internal, false, "The capture job registry is internally inconsistent."),
    ("offprint.runtime.lock", Internal, false, "A runtime state lock is poisoned."),
    ("offprint.runtime.shutdown", Shutdown, false, "Runtime shutdown did not complete cleanly."),
    ("offprint.runtime.signal", Shutdown, false, "The command could not subscribe to interruption signals."),
    ("offprint.runtime.start", Internal, false, "The command runtime could not be started."),
    ("offprint.runtime.state_transition", Internal, false, "The capture state machine rejected a transition."),
    ("offprint.runtime.terminal_event", Internal, false, "A capture emitted more than one terminal event."),
    ("offprint.runtime.timeout", Shutdown, true, "The requested operation exceeded its total deadline."),
    ("offprint.scheduler.artifact_read", Internal, true, "A captured crawl artifact could not be read for link discovery."),
    ("offprint.scheduler.concurrency", Validation, false, "Scheduler concurrency is outside the supported range."),
    ("offprint.scheduler.depth", Validation, false, "Crawl depth is outside the supported range."),
    ("offprint.scheduler.failed", Internal, false, "One or more scheduled captures reached a failed terminal state."),
    ("offprint.scheduler.job_count", Validation, false, "The number of scheduled jobs is outside the supported range."),
    ("offprint.scheduler.job_id", Validation, false, "A batch job identifier is invalid or duplicated."),
    ("offprint.scheduler.manifest_mismatch", Validation, false, "Resume state belongs to a different scheduler plan."),
    ("offprint.scheduler.manifest_read", Validation, true, "Resume state could not be inspected or decoded."),
    ("offprint.scheduler.manifest_shape", Validation, false, "Resume state has an invalid or inconsistent record shape."),
    ("offprint.scheduler.manifest_write", Commit, true, "Resume state could not be staged or committed."),
    ("offprint.scheduler.output", Validation, false, "The scheduler output directory is unavailable."),
    ("offprint.scheduler.plan", Validation, false, "A scheduler plan could not be serialized."),
    ("offprint.scheduler.resume_credentials", Validation, false, "A scheduler plan with capture credentials cannot use persisted resume state."),
    ("offprint.scheduler.resume_target", Validation, false, "A resumable job does not have a persistent artifact target."),
    ("offprint.scheduler.state", Internal, false, "The scheduler reached an inconsistent internal state."),
    ("offprint.scheduler.url", Validation, false, "A crawl URL uses an unsupported scheme."),
    ("offprint.screenshot.encoding", Verification, false, "A screenshot response could not be decoded."),
    ("offprint.screenshot.protocol_shape", Verification, false, "A screenshot response did not match the pinned protocol shape."),
    ("offprint.selection.empty", Collection, false, "The selected document scope has no active top-level selection."),
    ("offprint.selector.invalid", Collection, false, "The DOM selector is not a valid CSS selector."),
    ("offprint.selector.not_found", Collection, false, "The top-level document has no element matching the DOM selector."),
    ("offprint.transform.document", Transform, false, "The document model is incomplete or inconsistent."),
    ("offprint.transform.node", Transform, false, "A document transform referenced an unknown node."),
    ("offprint.transform.node_limit", Transform, false, "A document exceeds the node identifier range."),
    ("offprint.transform.structural_repair", Transform, false, "The structural repair program is invalid or exceeds its bounds."),
    ("offprint.transform.visual_fallback", Transform, false, "A visual fallback could not be attached to its captured node."),
    ("offprint.verification.active_content", Verification, false, "The artifact contains active captured content."),
    ("offprint.verification.csp", Verification, false, "The artifact content security policy is inconsistent."),
    ("offprint.verification.embedded_resource", Verification, false, "An embedded resource is malformed or inconsistent with its manifest record."),
    ("offprint.verification.external_reference", Verification, false, "The artifact contains an external render-fetch reference."),
    ("offprint.verification.format", Verification, false, "The artifact format or schema is incompatible."),
    ("offprint.verification.frame", Verification, false, "An artifact frame could not be inspected during offline verification."),
    ("offprint.verification.frames", Verification, false, "The embedded frame graph is incomplete or inconsistent."),
    ("offprint.verification.manifest", Verification, false, "The artifact manifest is missing or malformed."),
    ("offprint.verification.network", Verification, false, "The artifact attempted a network request during offline verification."),
    ("offprint.verification.page_error", Verification, false, "The artifact raised a page error during offline verification."),
    ("offprint.verification.path", Verification, false, "The staged artifact path cannot be opened by the verifier."),
    ("offprint.verification.record", Verification, false, "The artifact verification record is inconsistent."),
    ("offprint.verification.reference", Verification, false, "The artifact contains an invalid controlled resource reference."),
    ("offprint.verification.resource_provenance", Verification, false, "An embedded resource has incomplete retrieval provenance."),
    ("offprint.verification.resource_summary", Verification, false, "The artifact resource summary is inconsistent."),
    ("offprint.verification.size", Verification, false, "The artifact size exceeds the supported range."),
    ("offprint.verification.structural_repair", Verification, false, "The artifact structural repair data is malformed or inconsistent."),
    ("offprint.verification.timeout", Verification, true, "Offline verification exceeded its deadline."),
    ("offprint.verification.unstable", Verification, true, "The artifact did not reach a stable browser state during offline verification."),
    ("offprint.visual_fallback.bounds", Collection, false, "A visual fallback has invalid or out-of-range browser bounds."),
    ("offprint.visual_fallback.encoding", Collection, false, "A visual fallback image could not be decoded."),
    ("offprint.visual_fallback.evaluate", Collection, false, "Visual fallback evaluation failed in the browser."),
    ("offprint.visual_fallback.frame", Collection, false, "A visual fallback frame is unavailable or inconsistent."),
    ("offprint.visual_fallback.frame_owner", Collection, false, "A visual fallback frame owner is unavailable or inconsistent."),
    ("offprint.visual_fallback.pixel_limit", Collection, false, "A visual fallback exceeds its configured pixel budget."),
    ("offprint.visual_fallback.protocol_shape", Collection, false, "A visual fallback response did not match the pinned protocol shape."),
    ("offprint.visual_fallback.viewport", Collection, false, "A visual fallback lies outside its browser viewport."),
];
