# Generated by `just codegen`. Do not edit.

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

ExportRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

class ExportRequestFormatSpecOneOf1(TypedDict):
    format: Literal["pdf"]
    options: ExportRequestPdfOptions

class ExportRequestFormatSpecOneOf2(TypedDict):
    format: Literal["markdown"]
    options: ExportRequestMarkdownOptions

class ExportRequestFormatSpecOneOf3(TypedDict):
    format: Literal["zip"]

class ExportRequestFormatSpecOneOf4(TypedDict):
    format: Literal["self-extracting-html"]

class ExportRequestFormatSpecOneOf5(TypedDict):
    format: Literal["mhtml"]

ExportRequestFormatSpec: TypeAlias = ExportRequestFormatSpecOneOf1 | ExportRequestFormatSpecOneOf2 | ExportRequestFormatSpecOneOf3 | ExportRequestFormatSpecOneOf4 | ExportRequestFormatSpecOneOf5

class _ExportRequestMarkdownOptionsOptional(TypedDict, total=False):
    frontMatter: bool

class ExportRequestMarkdownOptions(_ExportRequestMarkdownOptionsOptional):
    pass

class _ExportRequestPdfOptionsOptional(TypedDict, total=False):
    landscape: bool
    preferCssPageSize: bool

class ExportRequestPdfOptions(_ExportRequestPdfOptionsOptional):
    pass

class ExportRequest(TypedDict):
    baseName: str
    conflict: ExportRequestConflictPolicy
    formats: list[ExportRequestFormatSpec]
    outputDirectory: str
    schemaVersion: int

ExportResultArtifactFormat: TypeAlias = Literal["html", "pdf", "markdown", "zip", "self-extracting-html", "mhtml"]

class ExportResultExportedArtifact(TypedDict):
    bytes: int
    entrypoint: str
    format: ExportResultArtifactFormat
    path: str
    sha256: str
    verification: ExportResultFormatVerification

class ExportResultFormatVerification(TypedDict):
    bytes: int
    format: ExportResultArtifactFormat
    sha256: str

class ExportResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class ExportResult(TypedDict):
    artifacts: list[ExportResultExportedArtifact]
    capturePolicySha256: str
    resources: ExportResultResourceSummary
    schemaVersion: int
    sourceArtifactSha256: str

class ArtifactManifestBrowserEnvironment(TypedDict):
    colorScheme: ArtifactManifestColorScheme
    locale: str
    reducedMotion: ArtifactManifestReducedMotion
    timezone: str
    userAgent: ArtifactManifestUserAgentPolicy
    viewport: ArtifactManifestViewport

class _ArtifactManifestBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class ArtifactManifestBrowserInfo(_ArtifactManifestBrowserInfoOptional):
    product: ArtifactManifestBrowserProduct
    protocolVersion: str
    source: ArtifactManifestBrowserSource
    version: str

ArtifactManifestBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

ArtifactManifestBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

ArtifactManifestColorScheme: TypeAlias = Literal["light", "dark"]

ArtifactManifestExternalReason: TypeAlias = Literal["policy", "unsupported-scheme", "explicitly-preserved"]

class ArtifactManifestManifestGenerator(TypedDict):
    name: str
    version: str

class ArtifactManifestManifestSource(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

ArtifactManifestOmissionReason: TypeAlias = Literal["non-rendering", "sanitized", "sensitive", "limit"]

ArtifactManifestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class ArtifactManifestResourceError(TypedDict):
    code: str
    message: str
    retryable: bool

class ArtifactManifestResourceOutcomeOneOf1(TypedDict):
    bytes: int
    digest: str
    kind: Literal["embedded"]
    mediaType: str

class ArtifactManifestResourceOutcomeOneOf2(TypedDict):
    kind: Literal["external"]
    reason: ArtifactManifestExternalReason
    url: str
    urlSha256: str

class ArtifactManifestResourceOutcomeOneOf3(TypedDict):
    kind: Literal["omitted"]
    reason: ArtifactManifestOmissionReason

class ArtifactManifestResourceOutcomeOneOf4(TypedDict):
    error: ArtifactManifestResourceError
    kind: Literal["failed"]

ArtifactManifestResourceOutcome: TypeAlias = ArtifactManifestResourceOutcomeOneOf1 | ArtifactManifestResourceOutcomeOneOf2 | ArtifactManifestResourceOutcomeOneOf3 | ArtifactManifestResourceOutcomeOneOf4

class _ArtifactManifestResourceProvenanceOptional(TypedDict, total=False):
    redirects: list[str]
    status: int | None

class ArtifactManifestResourceProvenance(_ArtifactManifestResourceProvenanceOptional):
    finalUrl: str
    finalUrlSha256: str
    receivedBytes: int
    source: ArtifactManifestResourceRetrievalSource

class _ArtifactManifestResourceRecordOptional(TypedDict, total=False):
    provenance: ArtifactManifestResourceProvenance | None

class ArtifactManifestResourceRecord(_ArtifactManifestResourceRecordOptional):
    frameId: int
    id: int
    outcome: ArtifactManifestResourceOutcome
    requestedUrl: str
    requestedUrlSha256: str

ArtifactManifestResourceRetrievalSource: TypeAlias = Literal["inline-data", "observed-response", "browser-context-fetch", "owning-frame-read", "local-file-read"]

class ArtifactManifestResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _ArtifactManifestStructuralRepairOptional(TypedDict, total=False):
    scriptSha256: str | None

class ArtifactManifestStructuralRepair(_ArtifactManifestStructuralRepairOptional):
    applied: bool

class ArtifactManifestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class ArtifactManifestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

ArtifactManifestUserAgentPolicy: TypeAlias = ArtifactManifestUserAgentPolicyOneOf1 | ArtifactManifestUserAgentPolicyOneOf2

ArtifactManifestVerificationMode: TypeAlias = Literal["static", "offline"]

class ArtifactManifestViewState(TypedDict):
    scrollX: str
    scrollY: str

class ArtifactManifestViewport(TypedDict):
    height: int
    scale: int
    width: int

class _ArtifactManifestOptional(TypedDict, total=False):
    resourceRecords: list[ArtifactManifestResourceRecord]
    warningCodes: list[str]

class ArtifactManifest(_ArtifactManifestOptional):
    browser: ArtifactManifestBrowserInfo
    capturePolicySha256: str
    capturedAt: str
    environment: ArtifactManifestBrowserEnvironment
    formatVersion: int
    frames: int
    generator: ArtifactManifestManifestGenerator
    resources: ArtifactManifestResourceSummary
    schemaVersion: int
    source: ArtifactManifestManifestSource
    structuralRepair: ArtifactManifestStructuralRepair
    verificationMode: ArtifactManifestVerificationMode
    viewState: ArtifactManifestViewState

ArtifactVerificationArtifactFormat: TypeAlias = Literal["html", "pdf", "markdown", "zip", "self-extracting-html", "mhtml"]

ArtifactVerificationVerificationMethod: TypeAlias = Literal["static", "offline", "format-specific"]

class ArtifactVerification(TypedDict):
    bytes: int
    format: ArtifactVerificationArtifactFormat
    method: ArtifactVerificationVerificationMethod
    networkRequests: int
    schemaVersion: int
    sha256: str

FormatVerificationArtifactFormat: TypeAlias = Literal["html", "pdf", "markdown", "zip", "self-extracting-html", "mhtml"]

class FormatVerification(TypedDict):
    bytes: int
    format: FormatVerificationArtifactFormat
    sha256: str

class BatchRequestBatchJob(TypedDict):
    id: str
    request: BatchRequestCaptureRequest

class _BatchRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: BatchRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class BatchRequestBrowserCookie(_BatchRequestBrowserCookieOptional):
    name: str
    value: str

class BatchRequestBrowserEnvironment(TypedDict):
    colorScheme: BatchRequestColorScheme
    locale: str
    reducedMotion: BatchRequestReducedMotion
    timezone: str
    userAgent: BatchRequestUserAgentPolicy
    viewport: BatchRequestViewport

class BatchRequestBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class BatchRequestBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

class BatchRequestBrowserSpecOneOf3(TypedDict):
    kind: Literal["remote"]
    value: str

BatchRequestBrowserSpec: TypeAlias = BatchRequestBrowserSpecOneOf1 | BatchRequestBrowserSpecOneOf2 | BatchRequestBrowserSpecOneOf3

class _BatchRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[BatchRequestBrowserCookie]
    headers: list[BatchRequestRequestHeader]

class BatchRequestCaptureCredentials(_BatchRequestCaptureCredentialsOptional):
    pass

class BatchRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resourceRecursionDepth: int
    resources: int
    totalResourceBytes: int

class BatchRequestCaptureOutputOneOf1(TypedDict):
    conflict: BatchRequestConflictPolicy
    kind: Literal["file"]
    path: str

class BatchRequestCaptureOutputOneOf2(TypedDict):
    kind: Literal["memory"]
    maxBytes: int

BatchRequestCaptureOutput: TypeAlias = BatchRequestCaptureOutputOneOf1 | BatchRequestCaptureOutputOneOf2

class _BatchRequestCaptureRequestOptional(TypedDict, total=False):
    credentials: BatchRequestCaptureCredentials
    headed: bool | None

class BatchRequestCaptureRequest(_BatchRequestCaptureRequestOptional):
    browser: BatchRequestBrowserSpec
    content: BatchRequestContentPolicy
    diagnostics: BatchRequestDiagnosticsPolicy
    environment: BatchRequestBrowserEnvironment
    limits: BatchRequestCaptureLimits
    network: BatchRequestNetworkPolicy
    output: BatchRequestCaptureOutput
    readiness: BatchRequestReadinessPolicy
    schemaVersion: int
    url: str
    verification: BatchRequestVerificationMode

BatchRequestCaptureScope: TypeAlias = Literal["page", "selection"]

BatchRequestColorScheme: TypeAlias = Literal["light", "dark"]

BatchRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

class _BatchRequestContentPolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: BatchRequestOptimizationPolicy
    scope: BatchRequestCaptureScope
    selector: str | None

class BatchRequestContentPolicy(_BatchRequestContentPolicyOptional):
    missingResources: BatchRequestMissingResourcePolicy
    preservePasswordValues: bool

BatchRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _BatchRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None

class BatchRequestDiagnosticsPolicy(_BatchRequestDiagnosticsPolicyOptional):
    pass

class BatchRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class BatchRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: BatchRequestViewportSweepPolicy

BatchRequestLazyLoadPolicy: TypeAlias = BatchRequestLazyLoadPolicyOneOf1 | BatchRequestLazyLoadPolicyOneOf2

BatchRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class BatchRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class BatchRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class BatchRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class BatchRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: BatchRequestNetworkRules

BatchRequestNetworkPolicy: TypeAlias = BatchRequestNetworkPolicyOneOf1 | BatchRequestNetworkPolicyOneOf2 | BatchRequestNetworkPolicyOneOf3 | BatchRequestNetworkPolicyOneOf4

class _BatchRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class BatchRequestNetworkRules(_BatchRequestNetworkRulesOptional):
    pass

class _BatchRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class BatchRequestOptimizationPolicy(_BatchRequestOptimizationPolicyOptional):
    pass

BatchRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class BatchRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: BatchRequestLazyLoadPolicy
    mode: BatchRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

BatchRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class BatchRequestRequestHeader(TypedDict):
    name: str
    value: str

class _BatchRequestResumeOptionsOptional(TypedDict, total=False):
    retryFailed: bool

class BatchRequestResumeOptions(_BatchRequestResumeOptionsOptional):
    manifest: str

class BatchRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class BatchRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

BatchRequestUserAgentPolicy: TypeAlias = BatchRequestUserAgentPolicyOneOf1 | BatchRequestUserAgentPolicyOneOf2

BatchRequestVerificationMode: TypeAlias = Literal["static", "offline"]

class BatchRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class BatchRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _BatchRequestOptional(TypedDict, total=False):
    concurrency: int
    resume: BatchRequestResumeOptions | None

class BatchRequest(_BatchRequestOptional):
    jobs: list[BatchRequestBatchJob]
    schemaVersion: int

class BatchResultCaptureArtifactOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class BatchResultCaptureArtifactOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

BatchResultCaptureArtifact: TypeAlias = BatchResultCaptureArtifactOneOf1 | BatchResultCaptureArtifactOneOf2

class _BatchResultCaptureReceiptOptional(TypedDict, total=False):
    warnings: list[BatchResultCaptureWarning]

class BatchResultCaptureReceipt(_BatchResultCaptureReceiptOptional):
    artifact: BatchResultCaptureArtifact
    captureId: str
    resources: BatchResultResourceSummary
    schemaVersion: int
    source: BatchResultSourceSummary
    timings: BatchResultCaptureTimings
    verification: BatchResultVerificationReport

class BatchResultCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    readiness: int
    resources: int
    total: int
    transform: int
    validation: int
    verification: int

class _BatchResultCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class BatchResultCaptureWarning(_BatchResultCaptureWarningOptional):
    code: str
    message: str

BatchResultErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

BatchResultOffprintErrorDetails: TypeAlias = dict[str, object]

class _BatchResultOffprintErrorOptional(TypedDict, total=False):
    details: BatchResultOffprintErrorDetails
    diagnosticsPath: str | None
    source: BatchResultOffprintError | None

class BatchResultOffprintError(_BatchResultOffprintErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: BatchResultErrorStage

class BatchResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _BatchResultResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: BatchResultOffprintError | None
    ordinal: int | None
    url: str | None

class BatchResultResumeJobRecord(_BatchResultResumeJobRecordOptional):
    requestSha256: str
    status: BatchResultResumeJobStatus

BatchResultResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

class BatchResultScheduledCaptureOutcomeOneOf1(TypedDict):
    id: str
    requestSha256: str
    result: BatchResultCaptureReceipt
    status: Literal["succeeded"]

class BatchResultScheduledCaptureOutcomeOneOf2(TypedDict):
    error: BatchResultOffprintError
    id: str
    requestSha256: str
    status: Literal["failed"]

class BatchResultScheduledCaptureOutcomeOneOf3(TypedDict):
    id: str
    record: BatchResultResumeJobRecord
    status: Literal["resumed"]

BatchResultScheduledCaptureOutcome: TypeAlias = BatchResultScheduledCaptureOutcomeOneOf1 | BatchResultScheduledCaptureOutcomeOneOf2 | BatchResultScheduledCaptureOutcomeOneOf3

class BatchResultSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

BatchResultVerificationMode: TypeAlias = Literal["static", "offline"]

class BatchResultVerificationReport(TypedDict):
    artifactSha256: str
    bytes: int
    mode: BatchResultVerificationMode
    networkRequests: int
    schemaVersion: int

class BatchResult(TypedDict):
    failed: int
    outcomes: list[BatchResultScheduledCaptureOutcome]
    planSha256: str
    resumed: int
    schemaVersion: int
    succeeded: int

class BrowserDoctorReportBrowserCandidate(TypedDict):
    activeLeases: int
    browser: BrowserDoctorReportBrowserInfo
    priority: int
    reasonCode: str
    state: BrowserDoctorReportBrowserCandidateState

BrowserDoctorReportBrowserCandidateState: TypeAlias = Literal["selected", "compatible", "shadowed"]

class _BrowserDoctorReportBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class BrowserDoctorReportBrowserInfo(_BrowserDoctorReportBrowserInfoOptional):
    product: BrowserDoctorReportBrowserProduct
    protocolVersion: str
    source: BrowserDoctorReportBrowserSource
    version: str

BrowserDoctorReportBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

BrowserDoctorReportBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _BrowserDoctorReportCapabilityCheckOptional(TypedDict, total=False):
    capabilities: list[str]
    missingCapabilities: list[str]
    peerVersion: str | None

class BrowserDoctorReportCapabilityCheck(_BrowserDoctorReportCapabilityCheckOptional):
    compatible: bool
    hostVersion: str

BrowserDoctorReportConfigProvenance: TypeAlias = Literal["flag", "environment", "explicit-config", "profile", "user-config", "default"]

class BrowserDoctorReportEffectiveConfigValue(TypedDict):
    field: str
    provenance: BrowserDoctorReportConfigProvenance
    redacted: bool
    value: object

class _BrowserDoctorReportManagedBrowserStateOptional(TypedDict, total=False):
    installedRevisions: list[str]
    selectedRevision: str | None

class BrowserDoctorReportManagedBrowserState(_BrowserDoctorReportManagedBrowserStateOptional):
    cacheDir: str
    catalogVersion: str

class BrowserDoctorReportNetworkPolicySummary(TypedDict):
    permitsLoopbackInitialOrigin: bool
    permitsPrivateAddresses: bool
    policy: str
    revalidatesRedirects: bool

class _BrowserDoctorReportOutputCapabilityOptional(TypedDict, total=False):
    reasonCode: str | None

class BrowserDoctorReportOutputCapability(_BrowserDoctorReportOutputCapabilityOptional):
    atomicCreate: bool
    atomicReplace: bool
    directory: str
    writable: bool

class _BrowserDoctorReportRecoveryActionOptional(TypedDict, total=False):
    arguments: list[str]

class BrowserDoctorReportRecoveryAction(_BrowserDoctorReportRecoveryActionOptional):
    code: str
    command: str
    description: str

class _BrowserDoctorReportOptional(TypedDict, total=False):
    candidates: list[BrowserDoctorReportBrowserCandidate]
    configuration: list[BrowserDoctorReportEffectiveConfigValue]
    recovery: list[BrowserDoctorReportRecoveryAction]
    selected: BrowserDoctorReportBrowserInfo | None

class BrowserDoctorReport(_BrowserDoctorReportOptional):
    collector: BrowserDoctorReportCapabilityCheck
    managedCache: BrowserDoctorReportManagedBrowserState
    network: BrowserDoctorReportNetworkPolicySummary
    output: BrowserDoctorReportOutputCapability
    ready: bool
    schemaVersion: int

BrowserOperationResultBrowserAction: TypeAlias = Literal["install", "list", "remove"]

class BrowserOperationResultBrowserCandidate(TypedDict):
    activeLeases: int
    browser: BrowserOperationResultBrowserInfo
    priority: int
    reasonCode: str
    state: BrowserOperationResultBrowserCandidateState

BrowserOperationResultBrowserCandidateState: TypeAlias = Literal["selected", "compatible", "shadowed"]

class _BrowserOperationResultBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class BrowserOperationResultBrowserInfo(_BrowserOperationResultBrowserInfoOptional):
    product: BrowserOperationResultBrowserProduct
    protocolVersion: str
    source: BrowserOperationResultBrowserSource
    version: str

BrowserOperationResultBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

BrowserOperationResultBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _BrowserOperationResultOptional(TypedDict, total=False):
    browser: BrowserOperationResultBrowserInfo | None
    candidates: list[BrowserOperationResultBrowserCandidate]
    revision: str | None

class BrowserOperationResult(_BrowserOperationResultOptional):
    action: BrowserOperationResultBrowserAction
    cacheDir: str
    schemaVersion: int

class _CaptureEventBrowserInfoOptional(TypedDict, total=False):
    endpoint: str | None
    executablePath: str | None
    revision: str | None

class CaptureEventBrowserInfo(_CaptureEventBrowserInfoOptional):
    product: CaptureEventBrowserProduct
    protocolVersion: str
    source: CaptureEventBrowserSource
    version: str

CaptureEventBrowserProduct: TypeAlias = Literal["chrome", "chromium", "edge"]

CaptureEventBrowserSource: TypeAlias = Literal["managed", "system", "explicit", "remote"]

class _CaptureEventCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CaptureEventCaptureWarning(_CaptureEventCaptureWarningOptional):
    code: str
    message: str

CaptureEventErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

CaptureEventOffprintErrorDetails: TypeAlias = dict[str, object]

class _CaptureEventOffprintErrorOptional(TypedDict, total=False):
    details: CaptureEventOffprintErrorDetails
    diagnosticsPath: str | None
    source: CaptureEventOffprintError | None

class CaptureEventOffprintError(_CaptureEventOffprintErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: CaptureEventErrorStage

CaptureEventVerificationMode: TypeAlias = Literal["static", "offline"]

class CaptureEventVerificationReport(TypedDict):
    artifactSha256: str
    bytes: int
    mode: CaptureEventVerificationMode
    networkRequests: int
    schemaVersion: int

class CaptureEventOneOf1(TypedDict):
    captureId: str
    type: Literal["capture.started"]

class CaptureEventOneOf2(TypedDict):
    browser: CaptureEventBrowserInfo
    captureId: str
    type: Literal["browser.ready"]

class CaptureEventOneOf3(TypedDict):
    captureId: str
    type: Literal["navigation.started"]
    url: str

CaptureEventOneOf4 = TypedDict("CaptureEventOneOf4", {"captureId": str, "from": str, "status": int, "to": str, "type": Literal["navigation.redirected"]})

class CaptureEventOneOf5(TypedDict):
    captureId: str
    elapsed: int
    milestone: str
    type: Literal["readiness.changed"]

class CaptureEventOneOf6(TypedDict):
    captureId: str
    frameId: int
    nodes: int
    type: Literal["frame.collected"]

class CaptureEventOneOf7(TypedDict):
    captureId: str
    resourceId: int
    type: Literal["resource.discovered"]

class CaptureEventOneOf8(TypedDict):
    bytes: int
    captureId: str
    completed: int
    discovered: int
    type: Literal["resource.progress"]

class CaptureEventOneOf9(TypedDict):
    captureId: str
    type: Literal["transform.started"]

class CaptureEventOneOf10(TypedDict):
    bytes: int
    captureId: str
    type: Literal["artifact.encoding"]

class CaptureEventOneOf11(TypedDict):
    captureId: str
    type: Literal["verification.started"]

class CaptureEventOneOf12(TypedDict):
    captureId: str
    type: Literal["warning"]
    warning: CaptureEventCaptureWarning

class CaptureEventOneOf13(TypedDict):
    captureId: str
    type: Literal["capture.succeeded"]
    verification: CaptureEventVerificationReport

class CaptureEventOneOf14(TypedDict):
    captureId: str
    error: CaptureEventOffprintError
    type: Literal["capture.failed"]

class CaptureEventOneOf15(TypedDict):
    captureId: str
    type: Literal["capture.cancelled"]

CaptureEvent: TypeAlias = CaptureEventOneOf1 | CaptureEventOneOf2 | CaptureEventOneOf3 | CaptureEventOneOf4 | CaptureEventOneOf5 | CaptureEventOneOf6 | CaptureEventOneOf7 | CaptureEventOneOf8 | CaptureEventOneOf9 | CaptureEventOneOf10 | CaptureEventOneOf11 | CaptureEventOneOf12 | CaptureEventOneOf13 | CaptureEventOneOf14 | CaptureEventOneOf15

ContentPolicyCaptureScope: TypeAlias = Literal["page", "selection"]

ContentPolicyMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class _ContentPolicyOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class ContentPolicyOptimizationPolicy(_ContentPolicyOptimizationPolicyOptional):
    pass

class _ContentPolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: ContentPolicyOptimizationPolicy
    scope: ContentPolicyCaptureScope
    selector: str | None

class ContentPolicy(_ContentPolicyOptional):
    missingResources: ContentPolicyMissingResourcePolicy
    preservePasswordValues: bool

class _CaptureRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: CaptureRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class CaptureRequestBrowserCookie(_CaptureRequestBrowserCookieOptional):
    name: str
    value: str

class CaptureRequestBrowserEnvironment(TypedDict):
    colorScheme: CaptureRequestColorScheme
    locale: str
    reducedMotion: CaptureRequestReducedMotion
    timezone: str
    userAgent: CaptureRequestUserAgentPolicy
    viewport: CaptureRequestViewport

class CaptureRequestBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class CaptureRequestBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

class CaptureRequestBrowserSpecOneOf3(TypedDict):
    kind: Literal["remote"]
    value: str

CaptureRequestBrowserSpec: TypeAlias = CaptureRequestBrowserSpecOneOf1 | CaptureRequestBrowserSpecOneOf2 | CaptureRequestBrowserSpecOneOf3

class _CaptureRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[CaptureRequestBrowserCookie]
    headers: list[CaptureRequestRequestHeader]

class CaptureRequestCaptureCredentials(_CaptureRequestCaptureCredentialsOptional):
    pass

class CaptureRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resourceRecursionDepth: int
    resources: int
    totalResourceBytes: int

class CaptureRequestCaptureOutputOneOf1(TypedDict):
    conflict: CaptureRequestConflictPolicy
    kind: Literal["file"]
    path: str

class CaptureRequestCaptureOutputOneOf2(TypedDict):
    kind: Literal["memory"]
    maxBytes: int

CaptureRequestCaptureOutput: TypeAlias = CaptureRequestCaptureOutputOneOf1 | CaptureRequestCaptureOutputOneOf2

CaptureRequestCaptureScope: TypeAlias = Literal["page", "selection"]

CaptureRequestColorScheme: TypeAlias = Literal["light", "dark"]

CaptureRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

class _CaptureRequestContentPolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: CaptureRequestOptimizationPolicy
    scope: CaptureRequestCaptureScope
    selector: str | None

class CaptureRequestContentPolicy(_CaptureRequestContentPolicyOptional):
    missingResources: CaptureRequestMissingResourcePolicy
    preservePasswordValues: bool

CaptureRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _CaptureRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None

class CaptureRequestDiagnosticsPolicy(_CaptureRequestDiagnosticsPolicyOptional):
    pass

class CaptureRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class CaptureRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: CaptureRequestViewportSweepPolicy

CaptureRequestLazyLoadPolicy: TypeAlias = CaptureRequestLazyLoadPolicyOneOf1 | CaptureRequestLazyLoadPolicyOneOf2

CaptureRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class CaptureRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class CaptureRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class CaptureRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class CaptureRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: CaptureRequestNetworkRules

CaptureRequestNetworkPolicy: TypeAlias = CaptureRequestNetworkPolicyOneOf1 | CaptureRequestNetworkPolicyOneOf2 | CaptureRequestNetworkPolicyOneOf3 | CaptureRequestNetworkPolicyOneOf4

class _CaptureRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class CaptureRequestNetworkRules(_CaptureRequestNetworkRulesOptional):
    pass

class _CaptureRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class CaptureRequestOptimizationPolicy(_CaptureRequestOptimizationPolicyOptional):
    pass

CaptureRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class CaptureRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: CaptureRequestLazyLoadPolicy
    mode: CaptureRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

CaptureRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class CaptureRequestRequestHeader(TypedDict):
    name: str
    value: str

class CaptureRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class CaptureRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

CaptureRequestUserAgentPolicy: TypeAlias = CaptureRequestUserAgentPolicyOneOf1 | CaptureRequestUserAgentPolicyOneOf2

CaptureRequestVerificationMode: TypeAlias = Literal["static", "offline"]

class CaptureRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class CaptureRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _CaptureRequestOptional(TypedDict, total=False):
    credentials: CaptureRequestCaptureCredentials
    headed: bool | None

class CaptureRequest(_CaptureRequestOptional):
    browser: CaptureRequestBrowserSpec
    content: CaptureRequestContentPolicy
    diagnostics: CaptureRequestDiagnosticsPolicy
    environment: CaptureRequestBrowserEnvironment
    limits: CaptureRequestCaptureLimits
    network: CaptureRequestNetworkPolicy
    output: CaptureRequestCaptureOutput
    readiness: CaptureRequestReadinessPolicy
    schemaVersion: int
    url: str
    verification: CaptureRequestVerificationMode

class CaptureReceiptCaptureArtifactOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class CaptureReceiptCaptureArtifactOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

CaptureReceiptCaptureArtifact: TypeAlias = CaptureReceiptCaptureArtifactOneOf1 | CaptureReceiptCaptureArtifactOneOf2

class CaptureReceiptCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    readiness: int
    resources: int
    total: int
    transform: int
    validation: int
    verification: int

class _CaptureReceiptCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CaptureReceiptCaptureWarning(_CaptureReceiptCaptureWarningOptional):
    code: str
    message: str

class CaptureReceiptResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class CaptureReceiptSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

CaptureReceiptVerificationMode: TypeAlias = Literal["static", "offline"]

class CaptureReceiptVerificationReport(TypedDict):
    artifactSha256: str
    bytes: int
    mode: CaptureReceiptVerificationMode
    networkRequests: int
    schemaVersion: int

class _CaptureReceiptOptional(TypedDict, total=False):
    warnings: list[CaptureReceiptCaptureWarning]

class CaptureReceipt(_CaptureReceiptOptional):
    artifact: CaptureReceiptCaptureArtifact
    captureId: str
    resources: CaptureReceiptResourceSummary
    schemaVersion: int
    source: CaptureReceiptSourceSummary
    timings: CaptureReceiptCaptureTimings
    verification: CaptureReceiptVerificationReport

class _CrawlRequestBrowserCookieOptional(TypedDict, total=False):
    domain: str | None
    expires: int | None
    httpOnly: bool | None
    path: str | None
    sameSite: CrawlRequestCookieSameSite | None
    secure: bool | None
    url: str | None

class CrawlRequestBrowserCookie(_CrawlRequestBrowserCookieOptional):
    name: str
    value: str

class CrawlRequestBrowserEnvironment(TypedDict):
    colorScheme: CrawlRequestColorScheme
    locale: str
    reducedMotion: CrawlRequestReducedMotion
    timezone: str
    userAgent: CrawlRequestUserAgentPolicy
    viewport: CrawlRequestViewport

class _CrawlRequestCaptureCredentialsOptional(TypedDict, total=False):
    cookies: list[CrawlRequestBrowserCookie]
    headers: list[CrawlRequestRequestHeader]

class CrawlRequestCaptureCredentials(_CrawlRequestCaptureCredentialsOptional):
    pass

class CrawlRequestCaptureLimits(TypedDict):
    artifactBytes: int
    collectorChunkBytes: int
    concurrentResources: int
    duration: int
    frameDepth: int
    frames: int
    nodes: int
    redirects: int
    resourceBytes: int
    resourceRecursionDepth: int
    resources: int
    totalResourceBytes: int

class CrawlRequestCaptureOutputOneOf1(TypedDict):
    conflict: CrawlRequestConflictPolicy
    kind: Literal["file"]
    path: str

class CrawlRequestCaptureOutputOneOf2(TypedDict):
    kind: Literal["memory"]
    maxBytes: int

CrawlRequestCaptureOutput: TypeAlias = CrawlRequestCaptureOutputOneOf1 | CrawlRequestCaptureOutputOneOf2

CrawlRequestCaptureScope: TypeAlias = Literal["page", "selection"]

CrawlRequestColorScheme: TypeAlias = Literal["light", "dark"]

CrawlRequestConflictPolicy: TypeAlias = Literal["fail", "replace", "uniquify"]

class _CrawlRequestContentPolicyOptional(TypedDict, total=False):
    allowedFileRoots: list[str]
    optimizations: CrawlRequestOptimizationPolicy
    scope: CrawlRequestCaptureScope
    selector: str | None

class CrawlRequestContentPolicy(_CrawlRequestContentPolicyOptional):
    missingResources: CrawlRequestMissingResourcePolicy
    preservePasswordValues: bool

CrawlRequestCookieSameSite: TypeAlias = Literal["strict", "lax", "none"]

class _CrawlRequestDiagnosticsPolicyOptional(TypedDict, total=False):
    directory: str | None

class CrawlRequestDiagnosticsPolicy(_CrawlRequestDiagnosticsPolicyOptional):
    pass

class CrawlRequestLazyLoadPolicyOneOf1(TypedDict):
    kind: Literal["disabled"]

class CrawlRequestLazyLoadPolicyOneOf2(TypedDict):
    kind: Literal["viewport-sweep"]
    options: CrawlRequestViewportSweepPolicy

CrawlRequestLazyLoadPolicy: TypeAlias = CrawlRequestLazyLoadPolicyOneOf1 | CrawlRequestLazyLoadPolicyOneOf2

class CrawlRequestLocalBrowserSpecOneOf1(TypedDict):
    kind: Literal["auto"]

class CrawlRequestLocalBrowserSpecOneOf2(TypedDict):
    kind: Literal["executable"]
    value: str

CrawlRequestLocalBrowserSpec: TypeAlias = CrawlRequestLocalBrowserSpecOneOf1 | CrawlRequestLocalBrowserSpecOneOf2

class _CrawlRequestLocalCaptureRequestOptional(TypedDict, total=False):
    credentials: CrawlRequestCaptureCredentials
    headed: bool | None

class CrawlRequestLocalCaptureRequest(_CrawlRequestLocalCaptureRequestOptional):
    browser: CrawlRequestLocalBrowserSpec
    content: CrawlRequestContentPolicy
    diagnostics: CrawlRequestDiagnosticsPolicy
    environment: CrawlRequestBrowserEnvironment
    limits: CrawlRequestCaptureLimits
    network: CrawlRequestNetworkPolicy
    output: CrawlRequestCaptureOutput
    readiness: CrawlRequestReadinessPolicy
    schemaVersion: int
    url: str
    verification: CrawlRequestVerificationMode

CrawlRequestMissingResourcePolicy: TypeAlias = Literal["warn", "fail"]

class CrawlRequestNetworkPolicyOneOf1(TypedDict):
    kind: Literal["standard"]

class CrawlRequestNetworkPolicyOneOf2(TypedDict):
    kind: Literal["server"]

class CrawlRequestNetworkPolicyOneOf3(TypedDict):
    kind: Literal["unrestricted"]

class CrawlRequestNetworkPolicyOneOf4(TypedDict):
    kind: Literal["custom"]
    rules: CrawlRequestNetworkRules

CrawlRequestNetworkPolicy: TypeAlias = CrawlRequestNetworkPolicyOneOf1 | CrawlRequestNetworkPolicyOneOf2 | CrawlRequestNetworkPolicyOneOf3 | CrawlRequestNetworkPolicyOneOf4

class _CrawlRequestNetworkRulesOptional(TypedDict, total=False):
    allowLinkLocal: bool
    allowLoopback: bool
    allowPrivate: bool
    allowedCidrs: list[str]
    allowedHosts: list[str]

class CrawlRequestNetworkRules(_CrawlRequestNetworkRulesOptional):
    pass

class _CrawlRequestOptimizationPolicyOptional(TypedDict, total=False):
    removeHiddenElements: bool
    removeUnusedCss: bool
    removeUnusedFonts: bool

class CrawlRequestOptimizationPolicy(_CrawlRequestOptimizationPolicyOptional):
    pass

CrawlRequestReadinessMode: TypeAlias = Literal["render-idle", "network-idle", "load", "dom-content-loaded"]

class CrawlRequestReadinessPolicy(TypedDict):
    delay: int
    lazyLoad: CrawlRequestLazyLoadPolicy
    mode: CrawlRequestReadinessMode
    mutationQuiet: int
    networkQuiet: int

CrawlRequestReducedMotion: TypeAlias = Literal["reduce", "no-preference"]

class CrawlRequestRequestHeader(TypedDict):
    name: str
    value: str

class _CrawlRequestResumeOptionsOptional(TypedDict, total=False):
    retryFailed: bool

class CrawlRequestResumeOptions(_CrawlRequestResumeOptionsOptional):
    manifest: str

class CrawlRequestUserAgentPolicyOneOf1(TypedDict):
    kind: Literal["browser-default"]

class CrawlRequestUserAgentPolicyOneOf2(TypedDict):
    kind: Literal["override"]
    value: str

CrawlRequestUserAgentPolicy: TypeAlias = CrawlRequestUserAgentPolicyOneOf1 | CrawlRequestUserAgentPolicyOneOf2

CrawlRequestVerificationMode: TypeAlias = Literal["static", "offline"]

class CrawlRequestViewport(TypedDict):
    height: int
    scale: int
    width: int

class CrawlRequestViewportSweepPolicy(TypedDict):
    maxSteps: int
    settle: int
    stepPixels: int

class _CrawlRequestOptional(TypedDict, total=False):
    concurrency: int
    maximumDepth: int
    maximumPages: int
    resume: CrawlRequestResumeOptions | None
    sameOrigin: bool

class CrawlRequest(_CrawlRequestOptional):
    outputDirectory: str
    schemaVersion: int
    seed: CrawlRequestLocalCaptureRequest

class CrawlResultCaptureArtifactOneOf1(TypedDict):
    bytes: int
    kind: Literal["file"]
    path: str
    sha256: str

class CrawlResultCaptureArtifactOneOf2(TypedDict):
    bytes: int
    content: list[int]
    kind: Literal["bytes"]
    sha256: str

CrawlResultCaptureArtifact: TypeAlias = CrawlResultCaptureArtifactOneOf1 | CrawlResultCaptureArtifactOneOf2

class _CrawlResultCaptureReceiptOptional(TypedDict, total=False):
    warnings: list[CrawlResultCaptureWarning]

class CrawlResultCaptureReceipt(_CrawlResultCaptureReceiptOptional):
    artifact: CrawlResultCaptureArtifact
    captureId: str
    resources: CrawlResultResourceSummary
    schemaVersion: int
    source: CrawlResultSourceSummary
    timings: CrawlResultCaptureTimings
    verification: CrawlResultVerificationReport

class CrawlResultCaptureTimings(TypedDict):
    browser: int
    collection: int
    commit: int
    encoding: int
    navigation: int
    readiness: int
    resources: int
    total: int
    transform: int
    validation: int
    verification: int

class _CrawlResultCaptureWarningOptional(TypedDict, total=False):
    frameId: int | None
    resourceId: int | None

class CrawlResultCaptureWarning(_CrawlResultCaptureWarningOptional):
    code: str
    message: str

class CrawlResultCrawlPageOutcome(TypedDict):
    capture: CrawlResultScheduledCaptureOutcome
    depth: int
    ordinal: int
    url: str

CrawlResultErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

CrawlResultOffprintErrorDetails: TypeAlias = dict[str, object]

class _CrawlResultOffprintErrorOptional(TypedDict, total=False):
    details: CrawlResultOffprintErrorDetails
    diagnosticsPath: str | None
    source: CrawlResultOffprintError | None

class CrawlResultOffprintError(_CrawlResultOffprintErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: CrawlResultErrorStage

class CrawlResultResourceSummary(TypedDict):
    discovered: int
    embedded: int
    embeddedBytes: int
    external: int
    failed: int
    omitted: int

class _CrawlResultResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: CrawlResultOffprintError | None
    ordinal: int | None
    url: str | None

class CrawlResultResumeJobRecord(_CrawlResultResumeJobRecordOptional):
    requestSha256: str
    status: CrawlResultResumeJobStatus

CrawlResultResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

class CrawlResultScheduledCaptureOutcomeOneOf1(TypedDict):
    id: str
    requestSha256: str
    result: CrawlResultCaptureReceipt
    status: Literal["succeeded"]

class CrawlResultScheduledCaptureOutcomeOneOf2(TypedDict):
    error: CrawlResultOffprintError
    id: str
    requestSha256: str
    status: Literal["failed"]

class CrawlResultScheduledCaptureOutcomeOneOf3(TypedDict):
    id: str
    record: CrawlResultResumeJobRecord
    status: Literal["resumed"]

CrawlResultScheduledCaptureOutcome: TypeAlias = CrawlResultScheduledCaptureOutcomeOneOf1 | CrawlResultScheduledCaptureOutcomeOneOf2 | CrawlResultScheduledCaptureOutcomeOneOf3

class CrawlResultSourceSummary(TypedDict):
    finalUrl: str
    finalUrlSha256: str
    requestedUrl: str
    requestedUrlSha256: str

CrawlResultVerificationMode: TypeAlias = Literal["static", "offline"]

class CrawlResultVerificationReport(TypedDict):
    artifactSha256: str
    bytes: int
    mode: CrawlResultVerificationMode
    networkRequests: int
    schemaVersion: int

class CrawlResult(TypedDict):
    failed: int
    outcomes: list[CrawlResultCrawlPageOutcome]
    planSha256: str
    resumed: int
    schemaVersion: int
    succeeded: int

OffprintErrorRecordErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

OffprintErrorRecordDetails: TypeAlias = dict[str, object]

class _OffprintErrorRecordOptional(TypedDict, total=False):
    details: OffprintErrorRecordDetails
    diagnosticsPath: str | None
    source: OffprintErrorRecord | None

class OffprintErrorRecord(_OffprintErrorRecordOptional):
    code: str
    message: str
    retryable: bool
    stage: OffprintErrorRecordErrorStage

class ResumeManifestCrawlFrontierItem(TypedDict):
    depth: int
    ordinal: int
    url: str

ResumeManifestErrorStage: TypeAlias = Literal["validation", "browser", "navigation", "readiness", "collection", "resource", "transform", "encoding", "verification", "commit", "shutdown", "internal"]

ResumeManifestOffprintErrorDetails: TypeAlias = dict[str, object]

class _ResumeManifestOffprintErrorOptional(TypedDict, total=False):
    details: ResumeManifestOffprintErrorDetails
    diagnosticsPath: str | None
    source: ResumeManifestOffprintError | None

class ResumeManifestOffprintError(_ResumeManifestOffprintErrorOptional):
    code: str
    message: str
    retryable: bool
    stage: ResumeManifestErrorStage

class _ResumeManifestResumeJobRecordOptional(TypedDict, total=False):
    artifactPath: str | None
    artifactSha256: str | None
    captureId: str | None
    depth: int | None
    error: ResumeManifestOffprintError | None
    ordinal: int | None
    url: str | None

class ResumeManifestResumeJobRecord(_ResumeManifestResumeJobRecordOptional):
    requestSha256: str
    status: ResumeManifestResumeJobStatus

ResumeManifestResumeJobStatus: TypeAlias = Literal["succeeded", "failed"]

ResumeManifestScheduleKind: TypeAlias = Literal["batch", "crawl"]

ResumeManifestJobs: TypeAlias = dict[str, ResumeManifestResumeJobRecord]

class _ResumeManifestOptional(TypedDict, total=False):
    frontier: list[ResumeManifestCrawlFrontierItem]
    jobs: ResumeManifestJobs
    pending: list[str]

class ResumeManifest(_ResumeManifestOptional):
    kind: ResumeManifestScheduleKind
    planSha256: str
    schemaVersion: int

VerificationReportVerificationMode: TypeAlias = Literal["static", "offline"]

class VerificationReport(TypedDict):
    artifactSha256: str
    bytes: int
    mode: VerificationReportVerificationMode
    networkRequests: int
    schemaVersion: int

FormatSpec: TypeAlias = ExportRequestFormatSpec
ArtifactFormat: TypeAlias = FormatVerificationArtifactFormat
BatchJob: TypeAlias = BatchRequestBatchJob
BrowserInfo: TypeAlias = ArtifactManifestBrowserInfo
CaptureLimits: TypeAlias = CaptureRequestCaptureLimits
CaptureScope: TypeAlias = ContentPolicyCaptureScope
ConflictPolicy: TypeAlias = ExportRequestConflictPolicy
CrawlPageOutcome: TypeAlias = CrawlResultCrawlPageOutcome
ErrorStage: TypeAlias = OffprintErrorRecordErrorStage
ExportedArtifact: TypeAlias = ExportResultExportedArtifact
MarkdownOptions: TypeAlias = ExportRequestMarkdownOptions
PdfOptions: TypeAlias = ExportRequestPdfOptions
ResumeOptions: TypeAlias = BatchRequestResumeOptions
ScheduledCaptureOutcome: TypeAlias = BatchResultScheduledCaptureOutcome
VerificationMode: TypeAlias = VerificationReportVerificationMode
Viewport: TypeAlias = CaptureRequestViewport
