// Generated by `cargo run -p xtask -- codegen`. Do not edit.

type ArtifactExportRequestArtifactVariant = ({
  kind: "pdf";
  options: ArtifactExportRequestPdfOptions;
} | {
  kind: "markdown";
  options: ArtifactExportRequestMarkdownOptions;
} | {
  kind: "zip";
} | {
  kind: "self-extracting";
} | {
  kind: "mhtml";
});

type ArtifactExportRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type ArtifactExportRequestMarkdownOptions = {
  frontMatter?: boolean;
};

type ArtifactExportRequestPdfOptions = {
  landscape?: boolean;
  preferCssPageSize?: boolean;
};

export type ArtifactExportRequest = {
  baseName: string;
  conflict: ArtifactExportRequestConflictPolicy;
  outputDirectory: string;
  variants: Array<ArtifactExportRequestArtifactVariant>;
};

type ArtifactExportResultArtifactVariantKind = ("pdf" | "markdown" | "zip" | "self-extracting" | "mhtml");

type ArtifactExportResultArtifactVariantVerification = {
  bytes: number;
  contentValid: boolean;
  kind: ArtifactExportResultArtifactVariantKind;
  passed: boolean;
  sha256: string;
  structureValid: boolean;
};

type ArtifactExportResultExportedArtifact = {
  bytes: number;
  entrypoint: string;
  kind: ArtifactExportResultArtifactVariantKind;
  path: string;
  sha256: string;
  verification: ArtifactExportResultArtifactVariantVerification;
};

type ArtifactExportResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

export type ArtifactExportResult = {
  policySha256: string;
  resources: ArtifactExportResultResourceSummary;
  schemaVersion: number;
  sourceArtifactSha256: string;
  variants: Array<ArtifactExportResultExportedArtifact>;
};

type ArtifactManifestArtifactFormat = {
  kind: ArtifactManifestArtifactKind;
  version: number;
};

type ArtifactManifestArtifactKind = "html";

type ArtifactManifestBrowserEnvironment = {
  colorScheme: ArtifactManifestColorScheme;
  locale: string;
  reducedMotion: ArtifactManifestReducedMotion;
  timezone: string;
  userAgent: ArtifactManifestUserAgentPolicy;
  viewport: ArtifactManifestViewport;
};

type ArtifactManifestBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: ArtifactManifestBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: ArtifactManifestBrowserSource;
  version: string;
};

type ArtifactManifestBrowserProduct = ("chrome" | "chromium" | "edge");

type ArtifactManifestBrowserSource = ("managed" | "system" | "explicit" | "remote");

type ArtifactManifestColorScheme = ("light" | "dark");

type ArtifactManifestExternalReason = ("policy" | "unsupported-scheme" | "explicitly-preserved");

type ArtifactManifestManifestGenerator = {
  name: string;
  version: string;
};

type ArtifactManifestManifestSource = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type ArtifactManifestManifestVerification = {
  level: ArtifactManifestVerificationPolicy;
  networkRequests: number;
  passed: boolean;
};

type ArtifactManifestOmissionReason = ("non-rendering" | "sanitized" | "sensitive" | "limit");

type ArtifactManifestReducedMotion = ("reduce" | "no-preference");

type ArtifactManifestResourceError = {
  code: string;
  message: string;
  retryable: boolean;
};

type ArtifactManifestResourceOutcome = ({
  bytes: number;
  digest: string;
  kind: "embedded";
  mediaType: string;
} | {
  kind: "external";
  reason: ArtifactManifestExternalReason;
  url: string;
  urlSha256: string;
} | {
  kind: "omitted";
  reason: ArtifactManifestOmissionReason;
} | {
  error: ArtifactManifestResourceError;
  kind: "failed";
});

type ArtifactManifestResourceProvenance = {
  finalUrl: string;
  finalUrlSha256: string;
  receivedBytes: number;
  redirects?: Array<string>;
  source: ArtifactManifestResourceRetrievalSource;
  status?: (number | null);
};

type ArtifactManifestResourceRecord = {
  frameId: number;
  id: number;
  outcome: ArtifactManifestResourceOutcome;
  provenance?: (ArtifactManifestResourceProvenance | null);
  requestedUrl: string;
  requestedUrlSha256: string;
};

type ArtifactManifestResourceRetrievalSource = ("inline-data" | "observed-response" | "browser-context-fetch" | "owning-frame-read" | "local-file-read");

type ArtifactManifestResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type ArtifactManifestStructuralRepair = {
  applied: boolean;
  scriptSha256?: (string | null);
};

type ArtifactManifestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type ArtifactManifestVerificationPolicy = ("static" | "offline");

type ArtifactManifestViewState = {
  scrollX: string;
  scrollY: string;
};

type ArtifactManifestViewport = {
  height: number;
  scale: number;
  width: number;
};

export type ArtifactManifest = {
  browser: ArtifactManifestBrowserInfo;
  capturedAt: string;
  environment: ArtifactManifestBrowserEnvironment;
  format: ArtifactManifestArtifactFormat;
  frames: number;
  generator: ArtifactManifestManifestGenerator;
  policySha256: string;
  resourceRecords?: Array<ArtifactManifestResourceRecord>;
  resources: ArtifactManifestResourceSummary;
  schemaVersion: number;
  source: ArtifactManifestManifestSource;
  structuralRepair: ArtifactManifestStructuralRepair;
  verification: ArtifactManifestManifestVerification;
  viewState: ArtifactManifestViewState;
  warningCodes?: Array<string>;
};

type ArtifactVariantVerificationArtifactVariantKind = ("pdf" | "markdown" | "zip" | "self-extracting" | "mhtml");

export type ArtifactVariantVerification = {
  bytes: number;
  contentValid: boolean;
  kind: ArtifactVariantVerificationArtifactVariantKind;
  passed: boolean;
  sha256: string;
  structureValid: boolean;
};

type BatchRequestArtifactSpec = {
  kind: "html";
  options: BatchRequestHtmlArtifactSpec;
};

type BatchRequestArtifactTarget = ({
  kind: "file";
  value: string;
} | {
  kind: "bytes";
  value: {
    maxBytes: number;
  };
});

type BatchRequestBatchJob = {
  id: string;
  request: BatchRequestCaptureRequest;
};

type BatchRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (BatchRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type BatchRequestBrowserEnvironment = {
  colorScheme: BatchRequestColorScheme;
  locale: string;
  reducedMotion: BatchRequestReducedMotion;
  timezone: string;
  userAgent: BatchRequestUserAgentPolicy;
  viewport: BatchRequestViewport;
};

type BatchRequestBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
} | {
  kind: "remote";
  value: string;
});

type BatchRequestCaptureCredentials = {
  cookies?: Array<BatchRequestBrowserCookie>;
  headers?: Array<BatchRequestRequestHeader>;
};

type BatchRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type BatchRequestCapturePolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: BatchRequestMissingResourcePolicy;
  optimizations?: BatchRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: BatchRequestCaptureScope;
  selector?: (string | null);
};

type BatchRequestCaptureRequest = {
  artifact: BatchRequestArtifactSpec;
  browser: BatchRequestBrowserSpec;
  capture: BatchRequestCapturePolicy;
  credentials?: BatchRequestCaptureCredentials;
  diagnostics: BatchRequestDiagnosticsPolicy;
  environment: BatchRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: BatchRequestCaptureLimits;
  network: BatchRequestNetworkPolicy;
  readiness: BatchRequestReadinessPolicy;
  url: string;
  verification: BatchRequestVerificationPolicy;
};

type BatchRequestCaptureScope = ("page" | "selection");

type BatchRequestColorScheme = ("light" | "dark");

type BatchRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type BatchRequestCookieSameSite = ("strict" | "lax" | "none");

type BatchRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type BatchRequestHtmlArtifactSpec = {
  conflict: BatchRequestConflictPolicy;
  target: BatchRequestArtifactTarget;
};

type BatchRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: BatchRequestViewportSweepPolicy;
});

type BatchRequestMissingResourcePolicy = ("warn" | "fail");

type BatchRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: BatchRequestNetworkRules;
});

type BatchRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type BatchRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type BatchRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type BatchRequestReadinessPolicy = {
  delay: number;
  lazyLoad: BatchRequestLazyLoadPolicy;
  mode: BatchRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type BatchRequestReducedMotion = ("reduce" | "no-preference");

type BatchRequestRequestHeader = {
  name: string;
  value: string;
};

type BatchRequestResumeOptions = {
  manifest: string;
  retryFailed?: boolean;
};

type BatchRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type BatchRequestVerificationPolicy = ("static" | "offline");

type BatchRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type BatchRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type BatchRequest = {
  concurrency?: number;
  jobs: Array<BatchRequestBatchJob>;
  resume?: (BatchRequestResumeOptions | null);
};

type BatchResultArtifactResult = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type BatchResultCaptureResult = {
  artifact: BatchResultArtifactResult;
  captureId: string;
  resources: BatchResultResourceSummary;
  schemaVersion: number;
  source: BatchResultSourceSummary;
  status: BatchResultCaptureTerminalStatus;
  timings: BatchResultCaptureTimings;
  verification: BatchResultVerificationResult;
  warnings?: Array<BatchResultCaptureWarning>;
};

type BatchResultCaptureTerminalStatus = ("succeeded" | "cancelled" | "failed");

type BatchResultCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  resources: number;
  settle: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type BatchResultCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type BatchResultErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type BatchResultPageKnotError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (BatchResultPageKnotError | null);
  stage: BatchResultErrorStage;
};

type BatchResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type BatchResultResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (BatchResultPageKnotError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: BatchResultResumeJobStatus;
  url?: (string | null);
};

type BatchResultResumeJobStatus = ("succeeded" | "failed");

type BatchResultScheduledCaptureOutcome = ({
  id: string;
  requestSha256: string;
  result: BatchResultCaptureResult;
  status: "succeeded";
} | {
  error: BatchResultPageKnotError;
  id: string;
  requestSha256: string;
  status: "failed";
} | {
  id: string;
  record: BatchResultResumeJobRecord;
  status: "resumed";
});

type BatchResultSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type BatchResultVerificationPolicy = ("static" | "offline");

type BatchResultVerificationResult = {
  artifactSha256: string;
  attemptedUrls?: Array<string>;
  bytes: number;
  frameFailures?: Array<number>;
  level: BatchResultVerificationPolicy;
  networkRequests: number;
  pageErrors?: Array<string>;
  passed: boolean;
  schemaVersion: number;
  stable: boolean;
};

export type BatchResult = {
  failed: number;
  outcomes: Array<BatchResultScheduledCaptureOutcome>;
  planSha256: string;
  resumed: number;
  schemaVersion: number;
  succeeded: number;
};

type BrowserDoctorReportBrowserCandidate = {
  activeLeases: number;
  browser: BrowserDoctorReportBrowserInfo;
  priority: number;
  reasonCode: string;
  state: BrowserDoctorReportBrowserCandidateState;
};

type BrowserDoctorReportBrowserCandidateState = ("selected" | "compatible" | "incompatible" | "shadowed");

type BrowserDoctorReportBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: BrowserDoctorReportBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: BrowserDoctorReportBrowserSource;
  version: string;
};

type BrowserDoctorReportBrowserProduct = ("chrome" | "chromium" | "edge");

type BrowserDoctorReportBrowserSource = ("managed" | "system" | "explicit" | "remote");

type BrowserDoctorReportCapabilityCheck = {
  capabilities?: Array<string>;
  compatible: boolean;
  hostVersion: string;
  missingCapabilities?: Array<string>;
  peerVersion?: (string | null);
};

type BrowserDoctorReportConfigProvenance = ("flag" | "environment" | "explicit-config" | "profile" | "user-config" | "default");

type BrowserDoctorReportEffectiveConfigValue = {
  field: string;
  provenance: BrowserDoctorReportConfigProvenance;
  redacted: boolean;
  value: unknown;
};

type BrowserDoctorReportManagedBrowserState = {
  cacheDir: string;
  catalogVersion: string;
  installedRevisions?: Array<string>;
  selectedRevision?: (string | null);
};

type BrowserDoctorReportNetworkPolicySummary = {
  permitsLoopbackInitialOrigin: boolean;
  permitsPrivateAddresses: boolean;
  profile: string;
  revalidatesRedirects: boolean;
};

type BrowserDoctorReportOutputCapability = {
  atomicCreate: boolean;
  atomicReplace: boolean;
  directory: string;
  reasonCode?: (string | null);
  writable: boolean;
};

type BrowserDoctorReportRecoveryAction = {
  arguments?: Array<string>;
  code: string;
  command: string;
  description: string;
};

export type BrowserDoctorReport = {
  candidates?: Array<BrowserDoctorReportBrowserCandidate>;
  collector: BrowserDoctorReportCapabilityCheck;
  configuration?: Array<BrowserDoctorReportEffectiveConfigValue>;
  managedCache: BrowserDoctorReportManagedBrowserState;
  network: BrowserDoctorReportNetworkPolicySummary;
  output: BrowserDoctorReportOutputCapability;
  ready: boolean;
  recovery?: Array<BrowserDoctorReportRecoveryAction>;
  schemaVersion: number;
  selected?: (BrowserDoctorReportBrowserInfo | null);
};

type BrowserOperationResultBrowserAction = ("install" | "list" | "remove");

type BrowserOperationResultBrowserCandidate = {
  activeLeases: number;
  browser: BrowserOperationResultBrowserInfo;
  priority: number;
  reasonCode: string;
  state: BrowserOperationResultBrowserCandidateState;
};

type BrowserOperationResultBrowserCandidateState = ("selected" | "compatible" | "incompatible" | "shadowed");

type BrowserOperationResultBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: BrowserOperationResultBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: BrowserOperationResultBrowserSource;
  version: string;
};

type BrowserOperationResultBrowserProduct = ("chrome" | "chromium" | "edge");

type BrowserOperationResultBrowserSource = ("managed" | "system" | "explicit" | "remote");

export type BrowserOperationResult = {
  action: BrowserOperationResultBrowserAction;
  browser?: (BrowserOperationResultBrowserInfo | null);
  cacheDir: string;
  candidates?: Array<BrowserOperationResultBrowserCandidate>;
  revision?: (string | null);
  schemaVersion: number;
};

type CaptureEventBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: CaptureEventBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: CaptureEventBrowserSource;
  version: string;
};

type CaptureEventBrowserProduct = ("chrome" | "chromium" | "edge");

type CaptureEventBrowserSource = ("managed" | "system" | "explicit" | "remote");

type CaptureEventCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CaptureEventErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type CaptureEventPageKnotError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (CaptureEventPageKnotError | null);
  stage: CaptureEventErrorStage;
};

type CaptureEventVerificationPolicy = ("static" | "offline");

type CaptureEventVerificationResult = {
  artifactSha256: string;
  attemptedUrls?: Array<string>;
  bytes: number;
  frameFailures?: Array<number>;
  level: CaptureEventVerificationPolicy;
  networkRequests: number;
  pageErrors?: Array<string>;
  passed: boolean;
  schemaVersion: number;
  stable: boolean;
};

export type CaptureEvent = ({
  captureId: string;
  type: "capture.started";
} | {
  browser: CaptureEventBrowserInfo;
  captureId: string;
  type: "browser.ready";
} | {
  captureId: string;
  type: "navigation.started";
  url: string;
} | {
  captureId: string;
  from: string;
  status: number;
  to: string;
  type: "navigation.redirected";
} | {
  captureId: string;
  elapsed: number;
  milestone: string;
  type: "readiness.changed";
} | {
  captureId: string;
  frameId: number;
  nodes: number;
  type: "frame.collected";
} | {
  captureId: string;
  resourceId: number;
  type: "resource.discovered";
} | {
  bytes: number;
  captureId: string;
  completed: number;
  discovered: number;
  type: "resource.progress";
} | {
  captureId: string;
  type: "transform.started";
} | {
  bytes: number;
  captureId: string;
  type: "artifact.encoding";
} | {
  captureId: string;
  type: "verification.started";
} | {
  captureId: string;
  type: "warning";
  warning: CaptureEventCaptureWarning;
} | {
  captureId: string;
  type: "capture.succeeded";
  verification: CaptureEventVerificationResult;
} | {
  captureId: string;
  error: CaptureEventPageKnotError;
  type: "capture.failed";
} | {
  captureId: string;
  type: "capture.cancelled";
});

type CapturePolicyCaptureScope = ("page" | "selection");

type CapturePolicyMissingResourcePolicy = ("warn" | "fail");

type CapturePolicyOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

export type CapturePolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: CapturePolicyMissingResourcePolicy;
  optimizations?: CapturePolicyOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: CapturePolicyCaptureScope;
  selector?: (string | null);
};

type CaptureRequestArtifactSpec = {
  kind: "html";
  options: CaptureRequestHtmlArtifactSpec;
};

type CaptureRequestArtifactTarget = ({
  kind: "file";
  value: string;
} | {
  kind: "bytes";
  value: {
    maxBytes: number;
  };
});

type CaptureRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (CaptureRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type CaptureRequestBrowserEnvironment = {
  colorScheme: CaptureRequestColorScheme;
  locale: string;
  reducedMotion: CaptureRequestReducedMotion;
  timezone: string;
  userAgent: CaptureRequestUserAgentPolicy;
  viewport: CaptureRequestViewport;
};

type CaptureRequestBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
} | {
  kind: "remote";
  value: string;
});

type CaptureRequestCaptureCredentials = {
  cookies?: Array<CaptureRequestBrowserCookie>;
  headers?: Array<CaptureRequestRequestHeader>;
};

type CaptureRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type CaptureRequestCapturePolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: CaptureRequestMissingResourcePolicy;
  optimizations?: CaptureRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: CaptureRequestCaptureScope;
  selector?: (string | null);
};

type CaptureRequestCaptureScope = ("page" | "selection");

type CaptureRequestColorScheme = ("light" | "dark");

type CaptureRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type CaptureRequestCookieSameSite = ("strict" | "lax" | "none");

type CaptureRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type CaptureRequestHtmlArtifactSpec = {
  conflict: CaptureRequestConflictPolicy;
  target: CaptureRequestArtifactTarget;
};

type CaptureRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: CaptureRequestViewportSweepPolicy;
});

type CaptureRequestMissingResourcePolicy = ("warn" | "fail");

type CaptureRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: CaptureRequestNetworkRules;
});

type CaptureRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type CaptureRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type CaptureRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type CaptureRequestReadinessPolicy = {
  delay: number;
  lazyLoad: CaptureRequestLazyLoadPolicy;
  mode: CaptureRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type CaptureRequestReducedMotion = ("reduce" | "no-preference");

type CaptureRequestRequestHeader = {
  name: string;
  value: string;
};

type CaptureRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type CaptureRequestVerificationPolicy = ("static" | "offline");

type CaptureRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type CaptureRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type CaptureRequest = {
  artifact: CaptureRequestArtifactSpec;
  browser: CaptureRequestBrowserSpec;
  capture: CaptureRequestCapturePolicy;
  credentials?: CaptureRequestCaptureCredentials;
  diagnostics: CaptureRequestDiagnosticsPolicy;
  environment: CaptureRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: CaptureRequestCaptureLimits;
  network: CaptureRequestNetworkPolicy;
  readiness: CaptureRequestReadinessPolicy;
  url: string;
  verification: CaptureRequestVerificationPolicy;
};

type CaptureResultArtifactResult = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type CaptureResultCaptureTerminalStatus = ("succeeded" | "cancelled" | "failed");

type CaptureResultCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  resources: number;
  settle: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type CaptureResultCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CaptureResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type CaptureResultSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type CaptureResultVerificationPolicy = ("static" | "offline");

type CaptureResultVerificationResult = {
  artifactSha256: string;
  attemptedUrls?: Array<string>;
  bytes: number;
  frameFailures?: Array<number>;
  level: CaptureResultVerificationPolicy;
  networkRequests: number;
  pageErrors?: Array<string>;
  passed: boolean;
  schemaVersion: number;
  stable: boolean;
};

export type CaptureResult = {
  artifact: CaptureResultArtifactResult;
  captureId: string;
  resources: CaptureResultResourceSummary;
  schemaVersion: number;
  source: CaptureResultSourceSummary;
  status: CaptureResultCaptureTerminalStatus;
  timings: CaptureResultCaptureTimings;
  verification: CaptureResultVerificationResult;
  warnings?: Array<CaptureResultCaptureWarning>;
};

type CrawlRequestArtifactSpec = {
  kind: "html";
  options: CrawlRequestHtmlArtifactSpec;
};

type CrawlRequestArtifactTarget = ({
  kind: "file";
  value: string;
} | {
  kind: "bytes";
  value: {
    maxBytes: number;
  };
});

type CrawlRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (CrawlRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type CrawlRequestBrowserEnvironment = {
  colorScheme: CrawlRequestColorScheme;
  locale: string;
  reducedMotion: CrawlRequestReducedMotion;
  timezone: string;
  userAgent: CrawlRequestUserAgentPolicy;
  viewport: CrawlRequestViewport;
};

type CrawlRequestCaptureCredentials = {
  cookies?: Array<CrawlRequestBrowserCookie>;
  headers?: Array<CrawlRequestRequestHeader>;
};

type CrawlRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type CrawlRequestCapturePolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: CrawlRequestMissingResourcePolicy;
  optimizations?: CrawlRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: CrawlRequestCaptureScope;
  selector?: (string | null);
};

type CrawlRequestCaptureScope = ("page" | "selection");

type CrawlRequestColorScheme = ("light" | "dark");

type CrawlRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type CrawlRequestCookieSameSite = ("strict" | "lax" | "none");

type CrawlRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type CrawlRequestHtmlArtifactSpec = {
  conflict: CrawlRequestConflictPolicy;
  target: CrawlRequestArtifactTarget;
};

type CrawlRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: CrawlRequestViewportSweepPolicy;
});

type CrawlRequestLocalBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
});

type CrawlRequestLocalCaptureRequest = {
  artifact: CrawlRequestArtifactSpec;
  browser: CrawlRequestLocalBrowserSpec;
  capture: CrawlRequestCapturePolicy;
  credentials?: CrawlRequestCaptureCredentials;
  diagnostics: CrawlRequestDiagnosticsPolicy;
  environment: CrawlRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: CrawlRequestCaptureLimits;
  network: CrawlRequestNetworkPolicy;
  readiness: CrawlRequestReadinessPolicy;
  url: string;
  verification: CrawlRequestVerificationPolicy;
};

type CrawlRequestMissingResourcePolicy = ("warn" | "fail");

type CrawlRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: CrawlRequestNetworkRules;
});

type CrawlRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type CrawlRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type CrawlRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type CrawlRequestReadinessPolicy = {
  delay: number;
  lazyLoad: CrawlRequestLazyLoadPolicy;
  mode: CrawlRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type CrawlRequestReducedMotion = ("reduce" | "no-preference");

type CrawlRequestRequestHeader = {
  name: string;
  value: string;
};

type CrawlRequestResumeOptions = {
  manifest: string;
  retryFailed?: boolean;
};

type CrawlRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type CrawlRequestVerificationPolicy = ("static" | "offline");

type CrawlRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type CrawlRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type CrawlRequest = {
  concurrency?: number;
  maximumDepth?: number;
  maximumPages?: number;
  outputDirectory: string;
  resume?: (CrawlRequestResumeOptions | null);
  sameOrigin?: boolean;
  seed: CrawlRequestLocalCaptureRequest;
};

type CrawlResultArtifactResult = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type CrawlResultCaptureResult = {
  artifact: CrawlResultArtifactResult;
  captureId: string;
  resources: CrawlResultResourceSummary;
  schemaVersion: number;
  source: CrawlResultSourceSummary;
  status: CrawlResultCaptureTerminalStatus;
  timings: CrawlResultCaptureTimings;
  verification: CrawlResultVerificationResult;
  warnings?: Array<CrawlResultCaptureWarning>;
};

type CrawlResultCaptureTerminalStatus = ("succeeded" | "cancelled" | "failed");

type CrawlResultCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  resources: number;
  settle: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type CrawlResultCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CrawlResultCrawlPageOutcome = {
  capture: CrawlResultScheduledCaptureOutcome;
  depth: number;
  ordinal: number;
  url: string;
};

type CrawlResultErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type CrawlResultPageKnotError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (CrawlResultPageKnotError | null);
  stage: CrawlResultErrorStage;
};

type CrawlResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type CrawlResultResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (CrawlResultPageKnotError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: CrawlResultResumeJobStatus;
  url?: (string | null);
};

type CrawlResultResumeJobStatus = ("succeeded" | "failed");

type CrawlResultScheduledCaptureOutcome = ({
  id: string;
  requestSha256: string;
  result: CrawlResultCaptureResult;
  status: "succeeded";
} | {
  error: CrawlResultPageKnotError;
  id: string;
  requestSha256: string;
  status: "failed";
} | {
  id: string;
  record: CrawlResultResumeJobRecord;
  status: "resumed";
});

type CrawlResultSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type CrawlResultVerificationPolicy = ("static" | "offline");

type CrawlResultVerificationResult = {
  artifactSha256: string;
  attemptedUrls?: Array<string>;
  bytes: number;
  frameFailures?: Array<number>;
  level: CrawlResultVerificationPolicy;
  networkRequests: number;
  pageErrors?: Array<string>;
  passed: boolean;
  schemaVersion: number;
  stable: boolean;
};

export type CrawlResult = {
  failed: number;
  outcomes: Array<CrawlResultCrawlPageOutcome>;
  planSha256: string;
  resumed: number;
  schemaVersion: number;
  succeeded: number;
};

type PageKnotErrorRecordErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

export type PageKnotErrorRecord = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (PageKnotErrorRecord | null);
  stage: PageKnotErrorRecordErrorStage;
};

type ResumeManifestCrawlFrontierItem = {
  depth: number;
  ordinal: number;
  url: string;
};

type ResumeManifestErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type ResumeManifestPageKnotError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (ResumeManifestPageKnotError | null);
  stage: ResumeManifestErrorStage;
};

type ResumeManifestResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (ResumeManifestPageKnotError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: ResumeManifestResumeJobStatus;
  url?: (string | null);
};

type ResumeManifestResumeJobStatus = ("succeeded" | "failed");

type ResumeManifestScheduleKind = ("batch" | "crawl");

export type ResumeManifest = {
  frontier?: Array<ResumeManifestCrawlFrontierItem>;
  jobs?: Record<string, ResumeManifestResumeJobRecord>;
  kind: ResumeManifestScheduleKind;
  pending?: Array<string>;
  planSha256: string;
  schemaVersion: number;
};

type VerificationResultVerificationPolicy = ("static" | "offline");

export type VerificationResult = {
  artifactSha256: string;
  attemptedUrls?: Array<string>;
  bytes: number;
  frameFailures?: Array<number>;
  level: VerificationResultVerificationPolicy;
  networkRequests: number;
  pageErrors?: Array<string>;
  passed: boolean;
  schemaVersion: number;
  stable: boolean;
};

export type ArtifactVariant = ArtifactExportRequestArtifactVariant;
export type ArtifactVariantKind = ArtifactVariantVerificationArtifactVariantKind;
export type BatchJob = BatchRequestBatchJob;
export type BrowserInfo = ArtifactManifestBrowserInfo;
export type CaptureLimits = CaptureRequestCaptureLimits;
export type CaptureScope = CapturePolicyCaptureScope;
export type ConflictPolicy = ArtifactExportRequestConflictPolicy;
export type CrawlPageOutcome = CrawlResultCrawlPageOutcome;
export type ErrorStage = PageKnotErrorRecordErrorStage;
export type ExportedArtifact = ArtifactExportResultExportedArtifact;
export type MarkdownOptions = ArtifactExportRequestMarkdownOptions;
export type PdfOptions = ArtifactExportRequestPdfOptions;
export type ResumeOptions = BatchRequestResumeOptions;
export type ScheduledCaptureOutcome = BatchResultScheduledCaptureOutcome;
export type VerificationPolicy = VerificationResultVerificationPolicy;
export type Viewport = CaptureRequestViewport;
