// Generated by `cargo run -p xtask -- codegen`. Do not edit.

type ExportRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type ExportRequestFormatSpec = ({
  format: "pdf";
  options: ExportRequestPdfOptions;
} | {
  format: "markdown";
  options: ExportRequestMarkdownOptions;
} | {
  format: "zip";
} | {
  format: "self-extracting-html";
} | {
  format: "mhtml";
});

type ExportRequestMarkdownOptions = {
  frontMatter?: boolean;
};

type ExportRequestPdfOptions = {
  landscape?: boolean;
  preferCssPageSize?: boolean;
};

export type ExportRequest = {
  baseName: string;
  conflict: ExportRequestConflictPolicy;
  formats: Array<ExportRequestFormatSpec>;
  outputDirectory: string;
  schemaVersion: number;
};

type ExportResultArtifactFormat = ("html" | "pdf" | "markdown" | "zip" | "self-extracting-html" | "mhtml");

type ExportResultExportedArtifact = {
  bytes: number;
  entrypoint: string;
  format: ExportResultArtifactFormat;
  path: string;
  sha256: string;
  verification: ExportResultFormatVerification;
};

type ExportResultFormatVerification = {
  bytes: number;
  format: ExportResultArtifactFormat;
  sha256: string;
};

type ExportResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

export type ExportResult = {
  artifacts: Array<ExportResultExportedArtifact>;
  capturePolicySha256: string;
  resources: ExportResultResourceSummary;
  schemaVersion: number;
  sourceArtifactSha256: string;
};

type ArtifactManifestBrowserEnvironment = {
  colorScheme: ArtifactManifestColorScheme;
  locale: string;
  reducedMotion: ArtifactManifestReducedMotion;
  timezone: string;
  userAgent: ArtifactManifestUserAgentPolicy;
  viewport: ArtifactManifestViewport;
};

type ArtifactManifestBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: ArtifactManifestBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: ArtifactManifestBrowserSource;
  version: string;
};

type ArtifactManifestBrowserProduct = ("chrome" | "chromium" | "edge");

type ArtifactManifestBrowserSource = ("managed" | "system" | "explicit" | "remote");

type ArtifactManifestColorScheme = ("light" | "dark");

type ArtifactManifestExternalReason = ("policy" | "unsupported-scheme" | "explicitly-preserved");

type ArtifactManifestManifestGenerator = {
  name: string;
  version: string;
};

type ArtifactManifestManifestSource = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type ArtifactManifestOmissionReason = ("non-rendering" | "sanitized" | "sensitive" | "limit");

type ArtifactManifestReducedMotion = ("reduce" | "no-preference");

type ArtifactManifestResourceError = {
  code: string;
  message: string;
  retryable: boolean;
};

type ArtifactManifestResourceOutcome = ({
  bytes: number;
  digest: string;
  kind: "embedded";
  mediaType: string;
} | {
  kind: "external";
  reason: ArtifactManifestExternalReason;
  url: string;
  urlSha256: string;
} | {
  kind: "omitted";
  reason: ArtifactManifestOmissionReason;
} | {
  error: ArtifactManifestResourceError;
  kind: "failed";
});

type ArtifactManifestResourceProvenance = {
  finalUrl: string;
  finalUrlSha256: string;
  receivedBytes: number;
  redirects?: Array<string>;
  source: ArtifactManifestResourceRetrievalSource;
  status?: (number | null);
};

type ArtifactManifestResourceRecord = {
  frameId: number;
  id: number;
  outcome: ArtifactManifestResourceOutcome;
  provenance?: (ArtifactManifestResourceProvenance | null);
  requestedUrl: string;
  requestedUrlSha256: string;
};

type ArtifactManifestResourceRetrievalSource = ("inline-data" | "observed-response" | "browser-context-fetch" | "owning-frame-read" | "local-file-read");

type ArtifactManifestResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type ArtifactManifestStructuralRepair = {
  applied: boolean;
  scriptSha256?: (string | null);
};

type ArtifactManifestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type ArtifactManifestVerificationMode = ("static" | "offline");

type ArtifactManifestViewState = {
  scrollX: string;
  scrollY: string;
};

type ArtifactManifestViewport = {
  height: number;
  scale: number;
  width: number;
};

export type ArtifactManifest = {
  browser: ArtifactManifestBrowserInfo;
  capturePolicySha256: string;
  capturedAt: string;
  environment: ArtifactManifestBrowserEnvironment;
  formatVersion: number;
  frames: number;
  generator: ArtifactManifestManifestGenerator;
  resourceRecords?: Array<ArtifactManifestResourceRecord>;
  resources: ArtifactManifestResourceSummary;
  schemaVersion: number;
  source: ArtifactManifestManifestSource;
  structuralRepair: ArtifactManifestStructuralRepair;
  verificationMode: ArtifactManifestVerificationMode;
  viewState: ArtifactManifestViewState;
  warningCodes?: Array<string>;
};

type ArtifactVerificationArtifactFormat = ("html" | "pdf" | "markdown" | "zip" | "self-extracting-html" | "mhtml");

type ArtifactVerificationVerificationMethod = ("static" | "offline" | "format-specific");

export type ArtifactVerification = {
  bytes: number;
  format: ArtifactVerificationArtifactFormat;
  method: ArtifactVerificationVerificationMethod;
  networkRequests: number;
  schemaVersion: number;
  sha256: string;
};

type FormatVerificationArtifactFormat = ("html" | "pdf" | "markdown" | "zip" | "self-extracting-html" | "mhtml");

export type FormatVerification = {
  bytes: number;
  format: FormatVerificationArtifactFormat;
  sha256: string;
};

type BatchRequestBatchJob = {
  id: string;
  request: BatchRequestCaptureRequest;
};

type BatchRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (BatchRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type BatchRequestBrowserEnvironment = {
  colorScheme: BatchRequestColorScheme;
  locale: string;
  reducedMotion: BatchRequestReducedMotion;
  timezone: string;
  userAgent: BatchRequestUserAgentPolicy;
  viewport: BatchRequestViewport;
};

type BatchRequestBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
} | {
  kind: "remote";
  value: string;
});

type BatchRequestCaptureCredentials = {
  cookies?: Array<BatchRequestBrowserCookie>;
  headers?: Array<BatchRequestRequestHeader>;
};

type BatchRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type BatchRequestCaptureOutput = ({
  conflict: BatchRequestConflictPolicy;
  kind: "file";
  path: string;
} | {
  kind: "memory";
  maxBytes: number;
});

type BatchRequestCaptureRequest = {
  browser: BatchRequestBrowserSpec;
  content: BatchRequestContentPolicy;
  credentials?: BatchRequestCaptureCredentials;
  diagnostics: BatchRequestDiagnosticsPolicy;
  environment: BatchRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: BatchRequestCaptureLimits;
  network: BatchRequestNetworkPolicy;
  output: BatchRequestCaptureOutput;
  readiness: BatchRequestReadinessPolicy;
  schemaVersion: number;
  url: string;
  verification: BatchRequestVerificationMode;
};

type BatchRequestCaptureScope = ("page" | "selection");

type BatchRequestColorScheme = ("light" | "dark");

type BatchRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type BatchRequestContentPolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: BatchRequestMissingResourcePolicy;
  optimizations?: BatchRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: BatchRequestCaptureScope;
  selector?: (string | null);
};

type BatchRequestCookieSameSite = ("strict" | "lax" | "none");

type BatchRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type BatchRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: BatchRequestViewportSweepPolicy;
});

type BatchRequestMissingResourcePolicy = ("warn" | "fail");

type BatchRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: BatchRequestNetworkRules;
});

type BatchRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type BatchRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type BatchRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type BatchRequestReadinessPolicy = {
  delay: number;
  lazyLoad: BatchRequestLazyLoadPolicy;
  mode: BatchRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type BatchRequestReducedMotion = ("reduce" | "no-preference");

type BatchRequestRequestHeader = {
  name: string;
  value: string;
};

type BatchRequestResumeOptions = {
  manifest: string;
  retryFailed?: boolean;
};

type BatchRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type BatchRequestVerificationMode = ("static" | "offline");

type BatchRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type BatchRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type BatchRequest = {
  concurrency?: number;
  jobs: Array<BatchRequestBatchJob>;
  resume?: (BatchRequestResumeOptions | null);
  schemaVersion: number;
};

type BatchResultCaptureArtifact = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type BatchResultCaptureReceipt = {
  artifact: BatchResultCaptureArtifact;
  captureId: string;
  resources: BatchResultResourceSummary;
  schemaVersion: number;
  source: BatchResultSourceSummary;
  timings: BatchResultCaptureTimings;
  verification: BatchResultVerificationReport;
  warnings?: Array<BatchResultCaptureWarning>;
};

type BatchResultCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  readiness: number;
  resources: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type BatchResultCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type BatchResultErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type BatchResultOffprintError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (BatchResultOffprintError | null);
  stage: BatchResultErrorStage;
};

type BatchResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type BatchResultResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (BatchResultOffprintError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: BatchResultResumeJobStatus;
  url?: (string | null);
};

type BatchResultResumeJobStatus = ("succeeded" | "failed");

type BatchResultScheduledCaptureOutcome = ({
  id: string;
  requestSha256: string;
  result: BatchResultCaptureReceipt;
  status: "succeeded";
} | {
  error: BatchResultOffprintError;
  id: string;
  requestSha256: string;
  status: "failed";
} | {
  id: string;
  record: BatchResultResumeJobRecord;
  status: "resumed";
});

type BatchResultSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type BatchResultVerificationMode = ("static" | "offline");

type BatchResultVerificationReport = {
  artifactSha256: string;
  bytes: number;
  mode: BatchResultVerificationMode;
  networkRequests: number;
  schemaVersion: number;
};

export type BatchResult = {
  failed: number;
  outcomes: Array<BatchResultScheduledCaptureOutcome>;
  planSha256: string;
  resumed: number;
  schemaVersion: number;
  succeeded: number;
};

type BrowserDoctorReportBrowserCandidate = {
  activeLeases: number;
  browser: BrowserDoctorReportBrowserInfo;
  priority: number;
  reasonCode: string;
  state: BrowserDoctorReportBrowserCandidateState;
};

type BrowserDoctorReportBrowserCandidateState = ("selected" | "compatible" | "shadowed");

type BrowserDoctorReportBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: BrowserDoctorReportBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: BrowserDoctorReportBrowserSource;
  version: string;
};

type BrowserDoctorReportBrowserProduct = ("chrome" | "chromium" | "edge");

type BrowserDoctorReportBrowserSource = ("managed" | "system" | "explicit" | "remote");

type BrowserDoctorReportCapabilityCheck = {
  capabilities?: Array<string>;
  compatible: boolean;
  hostVersion: string;
  missingCapabilities?: Array<string>;
  peerVersion?: (string | null);
};

type BrowserDoctorReportConfigProvenance = ("flag" | "environment" | "explicit-config" | "profile" | "user-config" | "default");

type BrowserDoctorReportEffectiveConfigValue = {
  field: string;
  provenance: BrowserDoctorReportConfigProvenance;
  redacted: boolean;
  value: unknown;
};

type BrowserDoctorReportManagedBrowserState = {
  cacheDir: string;
  catalogVersion: string;
  installedRevisions?: Array<string>;
  selectedRevision?: (string | null);
};

type BrowserDoctorReportNetworkPolicySummary = {
  permitsLoopbackInitialOrigin: boolean;
  permitsPrivateAddresses: boolean;
  profile: string;
  revalidatesRedirects: boolean;
};

type BrowserDoctorReportOutputCapability = {
  atomicCreate: boolean;
  atomicReplace: boolean;
  directory: string;
  reasonCode?: (string | null);
  writable: boolean;
};

type BrowserDoctorReportRecoveryAction = {
  arguments?: Array<string>;
  code: string;
  command: string;
  description: string;
};

export type BrowserDoctorReport = {
  candidates?: Array<BrowserDoctorReportBrowserCandidate>;
  collector: BrowserDoctorReportCapabilityCheck;
  configuration?: Array<BrowserDoctorReportEffectiveConfigValue>;
  managedCache: BrowserDoctorReportManagedBrowserState;
  network: BrowserDoctorReportNetworkPolicySummary;
  output: BrowserDoctorReportOutputCapability;
  ready: boolean;
  recovery?: Array<BrowserDoctorReportRecoveryAction>;
  schemaVersion: number;
  selected?: (BrowserDoctorReportBrowserInfo | null);
};

type BrowserOperationResultBrowserAction = ("install" | "list" | "remove");

type BrowserOperationResultBrowserCandidate = {
  activeLeases: number;
  browser: BrowserOperationResultBrowserInfo;
  priority: number;
  reasonCode: string;
  state: BrowserOperationResultBrowserCandidateState;
};

type BrowserOperationResultBrowserCandidateState = ("selected" | "compatible" | "shadowed");

type BrowserOperationResultBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: BrowserOperationResultBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: BrowserOperationResultBrowserSource;
  version: string;
};

type BrowserOperationResultBrowserProduct = ("chrome" | "chromium" | "edge");

type BrowserOperationResultBrowserSource = ("managed" | "system" | "explicit" | "remote");

export type BrowserOperationResult = {
  action: BrowserOperationResultBrowserAction;
  browser?: (BrowserOperationResultBrowserInfo | null);
  cacheDir: string;
  candidates?: Array<BrowserOperationResultBrowserCandidate>;
  revision?: (string | null);
  schemaVersion: number;
};

type CaptureEventBrowserInfo = {
  endpoint?: (string | null);
  executablePath?: (string | null);
  product: CaptureEventBrowserProduct;
  protocolVersion: string;
  revision?: (string | null);
  source: CaptureEventBrowserSource;
  version: string;
};

type CaptureEventBrowserProduct = ("chrome" | "chromium" | "edge");

type CaptureEventBrowserSource = ("managed" | "system" | "explicit" | "remote");

type CaptureEventCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CaptureEventErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type CaptureEventOffprintError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (CaptureEventOffprintError | null);
  stage: CaptureEventErrorStage;
};

type CaptureEventVerificationMode = ("static" | "offline");

type CaptureEventVerificationReport = {
  artifactSha256: string;
  bytes: number;
  mode: CaptureEventVerificationMode;
  networkRequests: number;
  schemaVersion: number;
};

export type CaptureEvent = ({
  captureId: string;
  type: "capture.started";
} | {
  browser: CaptureEventBrowserInfo;
  captureId: string;
  type: "browser.ready";
} | {
  captureId: string;
  type: "navigation.started";
  url: string;
} | {
  captureId: string;
  from: string;
  status: number;
  to: string;
  type: "navigation.redirected";
} | {
  captureId: string;
  elapsed: number;
  milestone: string;
  type: "readiness.changed";
} | {
  captureId: string;
  frameId: number;
  nodes: number;
  type: "frame.collected";
} | {
  captureId: string;
  resourceId: number;
  type: "resource.discovered";
} | {
  bytes: number;
  captureId: string;
  completed: number;
  discovered: number;
  type: "resource.progress";
} | {
  captureId: string;
  type: "transform.started";
} | {
  bytes: number;
  captureId: string;
  type: "artifact.encoding";
} | {
  captureId: string;
  type: "verification.started";
} | {
  captureId: string;
  type: "warning";
  warning: CaptureEventCaptureWarning;
} | {
  captureId: string;
  type: "capture.succeeded";
  verification: CaptureEventVerificationReport;
} | {
  captureId: string;
  error: CaptureEventOffprintError;
  type: "capture.failed";
} | {
  captureId: string;
  type: "capture.cancelled";
});

type ContentPolicyCaptureScope = ("page" | "selection");

type ContentPolicyMissingResourcePolicy = ("warn" | "fail");

type ContentPolicyOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

export type ContentPolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: ContentPolicyMissingResourcePolicy;
  optimizations?: ContentPolicyOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: ContentPolicyCaptureScope;
  selector?: (string | null);
};

type CaptureRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (CaptureRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type CaptureRequestBrowserEnvironment = {
  colorScheme: CaptureRequestColorScheme;
  locale: string;
  reducedMotion: CaptureRequestReducedMotion;
  timezone: string;
  userAgent: CaptureRequestUserAgentPolicy;
  viewport: CaptureRequestViewport;
};

type CaptureRequestBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
} | {
  kind: "remote";
  value: string;
});

type CaptureRequestCaptureCredentials = {
  cookies?: Array<CaptureRequestBrowserCookie>;
  headers?: Array<CaptureRequestRequestHeader>;
};

type CaptureRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type CaptureRequestCaptureOutput = ({
  conflict: CaptureRequestConflictPolicy;
  kind: "file";
  path: string;
} | {
  kind: "memory";
  maxBytes: number;
});

type CaptureRequestCaptureScope = ("page" | "selection");

type CaptureRequestColorScheme = ("light" | "dark");

type CaptureRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type CaptureRequestContentPolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: CaptureRequestMissingResourcePolicy;
  optimizations?: CaptureRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: CaptureRequestCaptureScope;
  selector?: (string | null);
};

type CaptureRequestCookieSameSite = ("strict" | "lax" | "none");

type CaptureRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type CaptureRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: CaptureRequestViewportSweepPolicy;
});

type CaptureRequestMissingResourcePolicy = ("warn" | "fail");

type CaptureRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: CaptureRequestNetworkRules;
});

type CaptureRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type CaptureRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type CaptureRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type CaptureRequestReadinessPolicy = {
  delay: number;
  lazyLoad: CaptureRequestLazyLoadPolicy;
  mode: CaptureRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type CaptureRequestReducedMotion = ("reduce" | "no-preference");

type CaptureRequestRequestHeader = {
  name: string;
  value: string;
};

type CaptureRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type CaptureRequestVerificationMode = ("static" | "offline");

type CaptureRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type CaptureRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type CaptureRequest = {
  browser: CaptureRequestBrowserSpec;
  content: CaptureRequestContentPolicy;
  credentials?: CaptureRequestCaptureCredentials;
  diagnostics: CaptureRequestDiagnosticsPolicy;
  environment: CaptureRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: CaptureRequestCaptureLimits;
  network: CaptureRequestNetworkPolicy;
  output: CaptureRequestCaptureOutput;
  readiness: CaptureRequestReadinessPolicy;
  schemaVersion: number;
  url: string;
  verification: CaptureRequestVerificationMode;
};

type CaptureReceiptCaptureArtifact = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type CaptureReceiptCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  readiness: number;
  resources: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type CaptureReceiptCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CaptureReceiptResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type CaptureReceiptSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type CaptureReceiptVerificationMode = ("static" | "offline");

type CaptureReceiptVerificationReport = {
  artifactSha256: string;
  bytes: number;
  mode: CaptureReceiptVerificationMode;
  networkRequests: number;
  schemaVersion: number;
};

export type CaptureReceipt = {
  artifact: CaptureReceiptCaptureArtifact;
  captureId: string;
  resources: CaptureReceiptResourceSummary;
  schemaVersion: number;
  source: CaptureReceiptSourceSummary;
  timings: CaptureReceiptCaptureTimings;
  verification: CaptureReceiptVerificationReport;
  warnings?: Array<CaptureReceiptCaptureWarning>;
};

type CrawlRequestBrowserCookie = {
  domain?: (string | null);
  expires?: (number | null);
  httpOnly?: (boolean | null);
  name: string;
  path?: (string | null);
  sameSite?: (CrawlRequestCookieSameSite | null);
  secure?: (boolean | null);
  url?: (string | null);
  value: string;
};

type CrawlRequestBrowserEnvironment = {
  colorScheme: CrawlRequestColorScheme;
  locale: string;
  reducedMotion: CrawlRequestReducedMotion;
  timezone: string;
  userAgent: CrawlRequestUserAgentPolicy;
  viewport: CrawlRequestViewport;
};

type CrawlRequestCaptureCredentials = {
  cookies?: Array<CrawlRequestBrowserCookie>;
  headers?: Array<CrawlRequestRequestHeader>;
};

type CrawlRequestCaptureLimits = {
  artifactBytes: number;
  collectorChunkBytes: number;
  concurrentResources: number;
  cssImportDepth: number;
  duration: number;
  frameDepth: number;
  frames: number;
  nodes: number;
  redirects: number;
  resourceBytes: number;
  resources: number;
  totalResourceBytes: number;
};

type CrawlRequestCaptureOutput = ({
  conflict: CrawlRequestConflictPolicy;
  kind: "file";
  path: string;
} | {
  kind: "memory";
  maxBytes: number;
});

type CrawlRequestCaptureScope = ("page" | "selection");

type CrawlRequestColorScheme = ("light" | "dark");

type CrawlRequestConflictPolicy = ("fail" | "replace" | "uniquify");

type CrawlRequestContentPolicy = {
  allowedFileRoots?: Array<string>;
  missingResources: CrawlRequestMissingResourcePolicy;
  optimizations?: CrawlRequestOptimizationPolicy;
  preservePasswordValues: boolean;
  scope?: CrawlRequestCaptureScope;
  selector?: (string | null);
};

type CrawlRequestCookieSameSite = ("strict" | "lax" | "none");

type CrawlRequestDiagnosticsPolicy = {
  directory?: (string | null);
  screenshots?: boolean;
};

type CrawlRequestLazyLoadPolicy = ({
  kind: "disabled";
} | {
  kind: "viewport-sweep";
  options: CrawlRequestViewportSweepPolicy;
});

type CrawlRequestLocalBrowserSpec = ({
  kind: "auto";
} | {
  kind: "executable";
  value: string;
});

type CrawlRequestLocalCaptureRequest = {
  browser: CrawlRequestLocalBrowserSpec;
  content: CrawlRequestContentPolicy;
  credentials?: CrawlRequestCaptureCredentials;
  diagnostics: CrawlRequestDiagnosticsPolicy;
  environment: CrawlRequestBrowserEnvironment;
  headed?: (boolean | null);
  limits: CrawlRequestCaptureLimits;
  network: CrawlRequestNetworkPolicy;
  output: CrawlRequestCaptureOutput;
  readiness: CrawlRequestReadinessPolicy;
  schemaVersion: number;
  url: string;
  verification: CrawlRequestVerificationMode;
};

type CrawlRequestMissingResourcePolicy = ("warn" | "fail");

type CrawlRequestNetworkPolicy = ({
  kind: "standard";
} | {
  kind: "server";
} | {
  kind: "unrestricted";
} | {
  kind: "custom";
  rules: CrawlRequestNetworkRules;
});

type CrawlRequestNetworkRules = {
  allowLinkLocal?: boolean;
  allowLoopback?: boolean;
  allowPrivate?: boolean;
  allowedCidrs?: Array<string>;
  allowedHosts?: Array<string>;
};

type CrawlRequestOptimizationPolicy = {
  removeHiddenElements?: boolean;
  removeUnusedCss?: boolean;
  removeUnusedFonts?: boolean;
};

type CrawlRequestReadinessMode = ("render-idle" | "network-idle" | "load" | "dom-content-loaded");

type CrawlRequestReadinessPolicy = {
  delay: number;
  lazyLoad: CrawlRequestLazyLoadPolicy;
  mode: CrawlRequestReadinessMode;
  mutationQuiet: number;
  networkQuiet: number;
};

type CrawlRequestReducedMotion = ("reduce" | "no-preference");

type CrawlRequestRequestHeader = {
  name: string;
  value: string;
};

type CrawlRequestResumeOptions = {
  manifest: string;
  retryFailed?: boolean;
};

type CrawlRequestUserAgentPolicy = ({
  kind: "browser-default";
} | {
  kind: "override";
  value: string;
});

type CrawlRequestVerificationMode = ("static" | "offline");

type CrawlRequestViewport = {
  height: number;
  scale: number;
  width: number;
};

type CrawlRequestViewportSweepPolicy = {
  maxSteps: number;
  settle: number;
  stepPixels: number;
};

export type CrawlRequest = {
  concurrency?: number;
  maximumDepth?: number;
  maximumPages?: number;
  outputDirectory: string;
  resume?: (CrawlRequestResumeOptions | null);
  sameOrigin?: boolean;
  schemaVersion: number;
  seed: CrawlRequestLocalCaptureRequest;
};

type CrawlResultCaptureArtifact = ({
  bytes: number;
  kind: "file";
  path: string;
  sha256: string;
} | {
  bytes: number;
  content: Array<number>;
  kind: "bytes";
  sha256: string;
});

type CrawlResultCaptureReceipt = {
  artifact: CrawlResultCaptureArtifact;
  captureId: string;
  resources: CrawlResultResourceSummary;
  schemaVersion: number;
  source: CrawlResultSourceSummary;
  timings: CrawlResultCaptureTimings;
  verification: CrawlResultVerificationReport;
  warnings?: Array<CrawlResultCaptureWarning>;
};

type CrawlResultCaptureTimings = {
  browser: number;
  collection: number;
  commit: number;
  encoding: number;
  navigation: number;
  readiness: number;
  resources: number;
  total: number;
  transform: number;
  validation: number;
  verification: number;
};

type CrawlResultCaptureWarning = {
  code: string;
  frameId?: (number | null);
  message: string;
  resourceId?: (number | null);
};

type CrawlResultCrawlPageOutcome = {
  capture: CrawlResultScheduledCaptureOutcome;
  depth: number;
  ordinal: number;
  url: string;
};

type CrawlResultErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type CrawlResultOffprintError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (CrawlResultOffprintError | null);
  stage: CrawlResultErrorStage;
};

type CrawlResultResourceSummary = {
  discovered: number;
  embedded: number;
  embeddedBytes: number;
  external: number;
  failed: number;
  omitted: number;
};

type CrawlResultResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (CrawlResultOffprintError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: CrawlResultResumeJobStatus;
  url?: (string | null);
};

type CrawlResultResumeJobStatus = ("succeeded" | "failed");

type CrawlResultScheduledCaptureOutcome = ({
  id: string;
  requestSha256: string;
  result: CrawlResultCaptureReceipt;
  status: "succeeded";
} | {
  error: CrawlResultOffprintError;
  id: string;
  requestSha256: string;
  status: "failed";
} | {
  id: string;
  record: CrawlResultResumeJobRecord;
  status: "resumed";
});

type CrawlResultSourceSummary = {
  finalUrl: string;
  finalUrlSha256: string;
  requestedUrl: string;
  requestedUrlSha256: string;
};

type CrawlResultVerificationMode = ("static" | "offline");

type CrawlResultVerificationReport = {
  artifactSha256: string;
  bytes: number;
  mode: CrawlResultVerificationMode;
  networkRequests: number;
  schemaVersion: number;
};

export type CrawlResult = {
  failed: number;
  outcomes: Array<CrawlResultCrawlPageOutcome>;
  planSha256: string;
  resumed: number;
  schemaVersion: number;
  succeeded: number;
};

type OffprintErrorRecordErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

export type OffprintErrorRecord = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (OffprintErrorRecord | null);
  stage: OffprintErrorRecordErrorStage;
};

type ResumeManifestCrawlFrontierItem = {
  depth: number;
  ordinal: number;
  url: string;
};

type ResumeManifestErrorStage = ("validation" | "browser" | "navigation" | "readiness" | "collection" | "resource" | "transform" | "encoding" | "verification" | "commit" | "shutdown" | "internal");

type ResumeManifestOffprintError = {
  code: string;
  details?: Record<string, unknown>;
  diagnosticsPath?: (string | null);
  message: string;
  retryable: boolean;
  source?: (ResumeManifestOffprintError | null);
  stage: ResumeManifestErrorStage;
};

type ResumeManifestResumeJobRecord = {
  artifactPath?: (string | null);
  artifactSha256?: (string | null);
  captureId?: (string | null);
  depth?: (number | null);
  error?: (ResumeManifestOffprintError | null);
  ordinal?: (number | null);
  requestSha256: string;
  status: ResumeManifestResumeJobStatus;
  url?: (string | null);
};

type ResumeManifestResumeJobStatus = ("succeeded" | "failed");

type ResumeManifestScheduleKind = ("batch" | "crawl");

export type ResumeManifest = {
  frontier?: Array<ResumeManifestCrawlFrontierItem>;
  jobs?: Record<string, ResumeManifestResumeJobRecord>;
  kind: ResumeManifestScheduleKind;
  pending?: Array<string>;
  planSha256: string;
  schemaVersion: number;
};

type VerificationReportVerificationMode = ("static" | "offline");

export type VerificationReport = {
  artifactSha256: string;
  bytes: number;
  mode: VerificationReportVerificationMode;
  networkRequests: number;
  schemaVersion: number;
};

export type FormatSpec = ExportRequestFormatSpec;
export type ArtifactFormat = FormatVerificationArtifactFormat;
export type BatchJob = BatchRequestBatchJob;
export type BrowserInfo = ArtifactManifestBrowserInfo;
export type CaptureLimits = CaptureRequestCaptureLimits;
export type CaptureScope = ContentPolicyCaptureScope;
export type ConflictPolicy = ExportRequestConflictPolicy;
export type CrawlPageOutcome = CrawlResultCrawlPageOutcome;
export type ErrorStage = OffprintErrorRecordErrorStage;
export type ExportedArtifact = ExportResultExportedArtifact;
export type MarkdownOptions = ExportRequestMarkdownOptions;
export type PdfOptions = ExportRequestPdfOptions;
export type ResumeOptions = BatchRequestResumeOptions;
export type ScheduledCaptureOutcome = BatchResultScheduledCaptureOutcome;
export type VerificationMode = VerificationReportVerificationMode;
export type Viewport = CaptureRequestViewport;
