/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeCaptureEvents {
  next(): Promise<any | null>
}

export declare class NativeCaptureJob {
  get id(): string
  get status(): string
  events(): NativeCaptureEvents
  cancel(): void
  result(): Promise<any>
}

export declare class NativePageKnot {
  static create(options?: any | undefined | null): NativePageKnot
  get initializationError(): any | null
  capture(url: string, options?: any | undefined | null): Promise<any>
  start(request: any): Promise<NativeCaptureJob>
  batch(request: any): Promise<any>
  crawl(request: any): Promise<any>
  inspect(path: string): Promise<any>
  verify(path: string, options?: any | undefined | null): Promise<any>
  exportArtifacts(path: string, request: any): Promise<any>
  verifyVariant(path: string, kind: string): Promise<any>
  ensureBrowser(): Promise<any>
  close(): Promise<void>
  closeBlocking(): void
}
