from collections.abc import Awaitable

class NativeCaptureEvents:
    def next_json(self) -> Awaitable[str | None]: ...

class NativeCaptureJob:
    @property
    def id(self) -> str: ...
    @property
    def status(self) -> str: ...
    def events(self) -> NativeCaptureEvents: ...
    def cancel(self) -> None: ...
    def result_json(self) -> Awaitable[str]: ...

class NativeOffprint:
    def __init__(self, options_json: str | None = None) -> None: ...
    def capture_json(
        self,
        url: str,
        options_json: str | None = None,
    ) -> Awaitable[str]: ...
    def request_json(
        self,
        url: str,
        options_json: str | None = None,
    ) -> str: ...
    def start(self, request_json: str) -> Awaitable[NativeCaptureJob]: ...
    def batch_json(self, request_json: str) -> Awaitable[str]: ...
    def crawl_json(self, request_json: str) -> Awaitable[str]: ...
    def inspect_json(self, path: str) -> Awaitable[str]: ...
    def verify_json(
        self,
        path: str,
        options_json: str | None = None,
    ) -> Awaitable[str]: ...
    def export_json(
        self,
        path: str,
        request_json: str,
    ) -> Awaitable[str]: ...
    def verify_format_json(
        self,
        path: str,
        kind: str,
    ) -> Awaitable[str]: ...
    def ensure_browser_json(self) -> Awaitable[str]: ...
    def list_browsers_json(self) -> Awaitable[str]: ...
    def install_browser_json(self, revision: str | None) -> Awaitable[str]: ...
    def remove_browser_json(self, revision: str, force: bool) -> Awaitable[str]: ...
    def doctor_json(self) -> Awaitable[str]: ...
    def close_idle_browser(self) -> Awaitable[None]: ...
    def close(self) -> Awaitable[None]: ...
    def close_blocking(self) -> None: ...
